package com.empirestateids.domain;

import java.io.Serializable;

public class AclEntry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_entry.id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_entry.acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Long aclObjectIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_entry.ace_order
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Integer aceOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_entry.sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Long sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_entry.mask
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Integer mask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_entry.granting
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Boolean granting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_entry.audit_success
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Boolean auditSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_entry.audit_failure
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Boolean auditFailure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_entry.id
     *
     * @return the value of acl_entry.id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_entry.id
     *
     * @param id the value for acl_entry.id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_entry.acl_object_identity
     *
     * @return the value of acl_entry.acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Long getAclObjectIdentity() {
        return aclObjectIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_entry.acl_object_identity
     *
     * @param aclObjectIdentity the value for acl_entry.acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setAclObjectIdentity(Long aclObjectIdentity) {
        this.aclObjectIdentity = aclObjectIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_entry.ace_order
     *
     * @return the value of acl_entry.ace_order
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Integer getAceOrder() {
        return aceOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_entry.ace_order
     *
     * @param aceOrder the value for acl_entry.ace_order
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setAceOrder(Integer aceOrder) {
        this.aceOrder = aceOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_entry.sid
     *
     * @return the value of acl_entry.sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_entry.sid
     *
     * @param sid the value for acl_entry.sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_entry.mask
     *
     * @return the value of acl_entry.mask
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Integer getMask() {
        return mask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_entry.mask
     *
     * @param mask the value for acl_entry.mask
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setMask(Integer mask) {
        this.mask = mask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_entry.granting
     *
     * @return the value of acl_entry.granting
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Boolean getGranting() {
        return granting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_entry.granting
     *
     * @param granting the value for acl_entry.granting
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setGranting(Boolean granting) {
        this.granting = granting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_entry.audit_success
     *
     * @return the value of acl_entry.audit_success
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Boolean getAuditSuccess() {
        return auditSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_entry.audit_success
     *
     * @param auditSuccess the value for acl_entry.audit_success
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setAuditSuccess(Boolean auditSuccess) {
        this.auditSuccess = auditSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_entry.audit_failure
     *
     * @return the value of acl_entry.audit_failure
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Boolean getAuditFailure() {
        return auditFailure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_entry.audit_failure
     *
     * @param auditFailure the value for acl_entry.audit_failure
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setAuditFailure(Boolean auditFailure) {
        this.auditFailure = auditFailure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AclEntry other = (AclEntry) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAclObjectIdentity() == null ? other.getAclObjectIdentity() == null : this.getAclObjectIdentity().equals(other.getAclObjectIdentity()))
            && (this.getAceOrder() == null ? other.getAceOrder() == null : this.getAceOrder().equals(other.getAceOrder()))
            && (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
            && (this.getMask() == null ? other.getMask() == null : this.getMask().equals(other.getMask()))
            && (this.getGranting() == null ? other.getGranting() == null : this.getGranting().equals(other.getGranting()))
            && (this.getAuditSuccess() == null ? other.getAuditSuccess() == null : this.getAuditSuccess().equals(other.getAuditSuccess()))
            && (this.getAuditFailure() == null ? other.getAuditFailure() == null : this.getAuditFailure().equals(other.getAuditFailure()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAclObjectIdentity() == null) ? 0 : getAclObjectIdentity().hashCode());
        result = prime * result + ((getAceOrder() == null) ? 0 : getAceOrder().hashCode());
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getMask() == null) ? 0 : getMask().hashCode());
        result = prime * result + ((getGranting() == null) ? 0 : getGranting().hashCode());
        result = prime * result + ((getAuditSuccess() == null) ? 0 : getAuditSuccess().hashCode());
        result = prime * result + ((getAuditFailure() == null) ? 0 : getAuditFailure().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", aclObjectIdentity=").append(aclObjectIdentity);
        sb.append(", aceOrder=").append(aceOrder);
        sb.append(", sid=").append(sid);
        sb.append(", mask=").append(mask);
        sb.append(", granting=").append(granting);
        sb.append(", auditSuccess=").append(auditSuccess);
        sb.append(", auditFailure=").append(auditFailure);
        sb.append("]");
        return sb.toString();
    }
}