package com.empirestateids.domain;

import java.io.Serializable;

public class AclObjectIdentity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_object_identity.id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_object_identity.object_id_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Long objectIdClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_object_identity.object_id_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Long objectIdIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_object_identity.parent_object
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Long parentObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_object_identity.owner_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Long ownerSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_object_identity.entries_inheriting
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Boolean entriesInheriting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_object_identity.id
     *
     * @return the value of acl_object_identity.id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_object_identity.id
     *
     * @param id the value for acl_object_identity.id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_object_identity.object_id_class
     *
     * @return the value of acl_object_identity.object_id_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Long getObjectIdClass() {
        return objectIdClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_object_identity.object_id_class
     *
     * @param objectIdClass the value for acl_object_identity.object_id_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setObjectIdClass(Long objectIdClass) {
        this.objectIdClass = objectIdClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_object_identity.object_id_identity
     *
     * @return the value of acl_object_identity.object_id_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Long getObjectIdIdentity() {
        return objectIdIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_object_identity.object_id_identity
     *
     * @param objectIdIdentity the value for acl_object_identity.object_id_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setObjectIdIdentity(Long objectIdIdentity) {
        this.objectIdIdentity = objectIdIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_object_identity.parent_object
     *
     * @return the value of acl_object_identity.parent_object
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Long getParentObject() {
        return parentObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_object_identity.parent_object
     *
     * @param parentObject the value for acl_object_identity.parent_object
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setParentObject(Long parentObject) {
        this.parentObject = parentObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_object_identity.owner_sid
     *
     * @return the value of acl_object_identity.owner_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Long getOwnerSid() {
        return ownerSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_object_identity.owner_sid
     *
     * @param ownerSid the value for acl_object_identity.owner_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setOwnerSid(Long ownerSid) {
        this.ownerSid = ownerSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_object_identity.entries_inheriting
     *
     * @return the value of acl_object_identity.entries_inheriting
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Boolean getEntriesInheriting() {
        return entriesInheriting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_object_identity.entries_inheriting
     *
     * @param entriesInheriting the value for acl_object_identity.entries_inheriting
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setEntriesInheriting(Boolean entriesInheriting) {
        this.entriesInheriting = entriesInheriting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AclObjectIdentity other = (AclObjectIdentity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getObjectIdClass() == null ? other.getObjectIdClass() == null : this.getObjectIdClass().equals(other.getObjectIdClass()))
            && (this.getObjectIdIdentity() == null ? other.getObjectIdIdentity() == null : this.getObjectIdIdentity().equals(other.getObjectIdIdentity()))
            && (this.getParentObject() == null ? other.getParentObject() == null : this.getParentObject().equals(other.getParentObject()))
            && (this.getOwnerSid() == null ? other.getOwnerSid() == null : this.getOwnerSid().equals(other.getOwnerSid()))
            && (this.getEntriesInheriting() == null ? other.getEntriesInheriting() == null : this.getEntriesInheriting().equals(other.getEntriesInheriting()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getObjectIdClass() == null) ? 0 : getObjectIdClass().hashCode());
        result = prime * result + ((getObjectIdIdentity() == null) ? 0 : getObjectIdIdentity().hashCode());
        result = prime * result + ((getParentObject() == null) ? 0 : getParentObject().hashCode());
        result = prime * result + ((getOwnerSid() == null) ? 0 : getOwnerSid().hashCode());
        result = prime * result + ((getEntriesInheriting() == null) ? 0 : getEntriesInheriting().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", objectIdClass=").append(objectIdClass);
        sb.append(", objectIdIdentity=").append(objectIdIdentity);
        sb.append(", parentObject=").append(parentObject);
        sb.append(", ownerSid=").append(ownerSid);
        sb.append(", entriesInheriting=").append(entriesInheriting);
        sb.append("]");
        return sb.toString();
    }
}