package com.empirestateids.domain;

import java.util.ArrayList;
import java.util.List;

public class AclObjectIdentityCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public AclObjectIdentityCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassIsNull() {
            addCriterion("object_id_class is null");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassIsNotNull() {
            addCriterion("object_id_class is not null");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassEqualTo(Long value) {
            addCriterion("object_id_class =", value, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassNotEqualTo(Long value) {
            addCriterion("object_id_class <>", value, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassGreaterThan(Long value) {
            addCriterion("object_id_class >", value, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassGreaterThanOrEqualTo(Long value) {
            addCriterion("object_id_class >=", value, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassLessThan(Long value) {
            addCriterion("object_id_class <", value, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassLessThanOrEqualTo(Long value) {
            addCriterion("object_id_class <=", value, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassIn(List<Long> values) {
            addCriterion("object_id_class in", values, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassNotIn(List<Long> values) {
            addCriterion("object_id_class not in", values, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassBetween(Long value1, Long value2) {
            addCriterion("object_id_class between", value1, value2, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdClassNotBetween(Long value1, Long value2) {
            addCriterion("object_id_class not between", value1, value2, "objectIdClass");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityIsNull() {
            addCriterion("object_id_identity is null");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityIsNotNull() {
            addCriterion("object_id_identity is not null");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityEqualTo(Long value) {
            addCriterion("object_id_identity =", value, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityNotEqualTo(Long value) {
            addCriterion("object_id_identity <>", value, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityGreaterThan(Long value) {
            addCriterion("object_id_identity >", value, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityGreaterThanOrEqualTo(Long value) {
            addCriterion("object_id_identity >=", value, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityLessThan(Long value) {
            addCriterion("object_id_identity <", value, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityLessThanOrEqualTo(Long value) {
            addCriterion("object_id_identity <=", value, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityIn(List<Long> values) {
            addCriterion("object_id_identity in", values, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityNotIn(List<Long> values) {
            addCriterion("object_id_identity not in", values, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityBetween(Long value1, Long value2) {
            addCriterion("object_id_identity between", value1, value2, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andObjectIdIdentityNotBetween(Long value1, Long value2) {
            addCriterion("object_id_identity not between", value1, value2, "objectIdIdentity");
            return (Criteria) this;
        }

        public Criteria andParentObjectIsNull() {
            addCriterion("parent_object is null");
            return (Criteria) this;
        }

        public Criteria andParentObjectIsNotNull() {
            addCriterion("parent_object is not null");
            return (Criteria) this;
        }

        public Criteria andParentObjectEqualTo(Long value) {
            addCriterion("parent_object =", value, "parentObject");
            return (Criteria) this;
        }

        public Criteria andParentObjectNotEqualTo(Long value) {
            addCriterion("parent_object <>", value, "parentObject");
            return (Criteria) this;
        }

        public Criteria andParentObjectGreaterThan(Long value) {
            addCriterion("parent_object >", value, "parentObject");
            return (Criteria) this;
        }

        public Criteria andParentObjectGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_object >=", value, "parentObject");
            return (Criteria) this;
        }

        public Criteria andParentObjectLessThan(Long value) {
            addCriterion("parent_object <", value, "parentObject");
            return (Criteria) this;
        }

        public Criteria andParentObjectLessThanOrEqualTo(Long value) {
            addCriterion("parent_object <=", value, "parentObject");
            return (Criteria) this;
        }

        public Criteria andParentObjectIn(List<Long> values) {
            addCriterion("parent_object in", values, "parentObject");
            return (Criteria) this;
        }

        public Criteria andParentObjectNotIn(List<Long> values) {
            addCriterion("parent_object not in", values, "parentObject");
            return (Criteria) this;
        }

        public Criteria andParentObjectBetween(Long value1, Long value2) {
            addCriterion("parent_object between", value1, value2, "parentObject");
            return (Criteria) this;
        }

        public Criteria andParentObjectNotBetween(Long value1, Long value2) {
            addCriterion("parent_object not between", value1, value2, "parentObject");
            return (Criteria) this;
        }

        public Criteria andOwnerSidIsNull() {
            addCriterion("owner_sid is null");
            return (Criteria) this;
        }

        public Criteria andOwnerSidIsNotNull() {
            addCriterion("owner_sid is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerSidEqualTo(Long value) {
            addCriterion("owner_sid =", value, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andOwnerSidNotEqualTo(Long value) {
            addCriterion("owner_sid <>", value, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andOwnerSidGreaterThan(Long value) {
            addCriterion("owner_sid >", value, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andOwnerSidGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_sid >=", value, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andOwnerSidLessThan(Long value) {
            addCriterion("owner_sid <", value, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andOwnerSidLessThanOrEqualTo(Long value) {
            addCriterion("owner_sid <=", value, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andOwnerSidIn(List<Long> values) {
            addCriterion("owner_sid in", values, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andOwnerSidNotIn(List<Long> values) {
            addCriterion("owner_sid not in", values, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andOwnerSidBetween(Long value1, Long value2) {
            addCriterion("owner_sid between", value1, value2, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andOwnerSidNotBetween(Long value1, Long value2) {
            addCriterion("owner_sid not between", value1, value2, "ownerSid");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingIsNull() {
            addCriterion("entries_inheriting is null");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingIsNotNull() {
            addCriterion("entries_inheriting is not null");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingEqualTo(Boolean value) {
            addCriterion("entries_inheriting =", value, "entriesInheriting");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingNotEqualTo(Boolean value) {
            addCriterion("entries_inheriting <>", value, "entriesInheriting");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingGreaterThan(Boolean value) {
            addCriterion("entries_inheriting >", value, "entriesInheriting");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingGreaterThanOrEqualTo(Boolean value) {
            addCriterion("entries_inheriting >=", value, "entriesInheriting");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingLessThan(Boolean value) {
            addCriterion("entries_inheriting <", value, "entriesInheriting");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingLessThanOrEqualTo(Boolean value) {
            addCriterion("entries_inheriting <=", value, "entriesInheriting");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingIn(List<Boolean> values) {
            addCriterion("entries_inheriting in", values, "entriesInheriting");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingNotIn(List<Boolean> values) {
            addCriterion("entries_inheriting not in", values, "entriesInheriting");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingBetween(Boolean value1, Boolean value2) {
            addCriterion("entries_inheriting between", value1, value2, "entriesInheriting");
            return (Criteria) this;
        }

        public Criteria andEntriesInheritingNotBetween(Boolean value1, Boolean value2) {
            addCriterion("entries_inheriting not between", value1, value2, "entriesInheriting");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table acl_object_identity
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 04 18:04:41 EDT 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}