package com.empirestateids.domain;

import java.io.Serializable;
import java.util.Date;

public class Address implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.contact_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer contactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address1
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private String address1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address2
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Short cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.state_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Short stateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.state_province
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private String stateProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.postal_zipcode
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private String postalZipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.country_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Long countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_type_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Byte addressTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.created
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer updatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.updated
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_id
     *
     * @return the value of address.address_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_id
     *
     * @param addressId the value for address.address_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.contact_id
     *
     * @return the value of address.contact_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.contact_id
     *
     * @param contactId the value for address.contact_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address1
     *
     * @return the value of address.address1
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address1
     *
     * @param address1 the value for address.address1
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address2
     *
     * @return the value of address.address2
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address2
     *
     * @param address2 the value for address.address2
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city_code
     *
     * @return the value of address.city_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Short getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city_code
     *
     * @param cityCode the value for address.city_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCityCode(Short cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.state_code
     *
     * @return the value of address.state_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Short getStateCode() {
        return stateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.state_code
     *
     * @param stateCode the value for address.state_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setStateCode(Short stateCode) {
        this.stateCode = stateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.state_province
     *
     * @return the value of address.state_province
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public String getStateProvince() {
        return stateProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.state_province
     *
     * @param stateProvince the value for address.state_province
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.postal_zipcode
     *
     * @return the value of address.postal_zipcode
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public String getPostalZipcode() {
        return postalZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.postal_zipcode
     *
     * @param postalZipcode the value for address.postal_zipcode
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setPostalZipcode(String postalZipcode) {
        this.postalZipcode = postalZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.country_code
     *
     * @return the value of address.country_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Long getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.country_code
     *
     * @param countryCode the value for address.country_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCountryCode(Long countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_type_code
     *
     * @return the value of address.address_type_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Byte getAddressTypeCode() {
        return addressTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_type_code
     *
     * @param addressTypeCode the value for address.address_type_code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setAddressTypeCode(Byte addressTypeCode) {
        this.addressTypeCode = addressTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.created_by_id
     *
     * @return the value of address.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.created_by_id
     *
     * @param createdById the value for address.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.created
     *
     * @return the value of address.created
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.created
     *
     * @param created the value for address.created
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.updated_by_id
     *
     * @return the value of address.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getUpdatedById() {
        return updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.updated_by_id
     *
     * @param updatedById the value for address.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setUpdatedById(Integer updatedById) {
        this.updatedById = updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.updated
     *
     * @return the value of address.updated
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.updated
     *
     * @param updated the value for address.updated
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Address other = (Address) that;
        return (this.getAddressId() == null ? other.getAddressId() == null : this.getAddressId().equals(other.getAddressId()))
            && (this.getContactId() == null ? other.getContactId() == null : this.getContactId().equals(other.getContactId()))
            && (this.getAddress1() == null ? other.getAddress1() == null : this.getAddress1().equals(other.getAddress1()))
            && (this.getAddress2() == null ? other.getAddress2() == null : this.getAddress2().equals(other.getAddress2()))
            && (this.getCityCode() == null ? other.getCityCode() == null : this.getCityCode().equals(other.getCityCode()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getStateCode() == null ? other.getStateCode() == null : this.getStateCode().equals(other.getStateCode()))
            && (this.getStateProvince() == null ? other.getStateProvince() == null : this.getStateProvince().equals(other.getStateProvince()))
            && (this.getPostalZipcode() == null ? other.getPostalZipcode() == null : this.getPostalZipcode().equals(other.getPostalZipcode()))
            && (this.getCountryCode() == null ? other.getCountryCode() == null : this.getCountryCode().equals(other.getCountryCode()))
            && (this.getAddressTypeCode() == null ? other.getAddressTypeCode() == null : this.getAddressTypeCode().equals(other.getAddressTypeCode()))
            && (this.getCreatedById() == null ? other.getCreatedById() == null : this.getCreatedById().equals(other.getCreatedById()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getUpdatedById() == null ? other.getUpdatedById() == null : this.getUpdatedById().equals(other.getUpdatedById()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAddressId() == null) ? 0 : getAddressId().hashCode());
        result = prime * result + ((getContactId() == null) ? 0 : getContactId().hashCode());
        result = prime * result + ((getAddress1() == null) ? 0 : getAddress1().hashCode());
        result = prime * result + ((getAddress2() == null) ? 0 : getAddress2().hashCode());
        result = prime * result + ((getCityCode() == null) ? 0 : getCityCode().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getStateCode() == null) ? 0 : getStateCode().hashCode());
        result = prime * result + ((getStateProvince() == null) ? 0 : getStateProvince().hashCode());
        result = prime * result + ((getPostalZipcode() == null) ? 0 : getPostalZipcode().hashCode());
        result = prime * result + ((getCountryCode() == null) ? 0 : getCountryCode().hashCode());
        result = prime * result + ((getAddressTypeCode() == null) ? 0 : getAddressTypeCode().hashCode());
        result = prime * result + ((getCreatedById() == null) ? 0 : getCreatedById().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getUpdatedById() == null) ? 0 : getUpdatedById().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", addressId=").append(addressId);
        sb.append(", contactId=").append(contactId);
        sb.append(", address1=").append(address1);
        sb.append(", address2=").append(address2);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", city=").append(city);
        sb.append(", stateCode=").append(stateCode);
        sb.append(", stateProvince=").append(stateProvince);
        sb.append(", postalZipcode=").append(postalZipcode);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", addressTypeCode=").append(addressTypeCode);
        sb.append(", createdById=").append(createdById);
        sb.append(", created=").append(created);
        sb.append(", updatedById=").append(updatedById);
        sb.append(", updated=").append(updated);
        sb.append("]");
        return sb.toString();
    }
}