package com.empirestateids.domain;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_id
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.source
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.outline
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private String outline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content_file
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private String contentFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.primary_img
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private String primaryImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_type
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private Integer articleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.created_by_id
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private Integer createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.created
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updated_by_id
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private Integer updatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updated
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private Date updated;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updated
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private String completed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_id
     *
     * @return the value of article.article_id
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author
     *
     * @return the value of article.author
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author
     *
     * @param author the value for article.author
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.source
     *
     * @return the value of article.source
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.source
     *
     * @param source the value for article.source
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.outline
     *
     * @return the value of article.outline
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public String getOutline() {
        return outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.outline
     *
     * @param outline the value for article.outline
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setOutline(String outline) {
        this.outline = outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content_file
     *
     * @return the value of article.content_file
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public String getContentFile() {
        return contentFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content_file
     *
     * @param contentFile the value for article.content_file
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setContentFile(String contentFile) {
        this.contentFile = contentFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.primary_img
     *
     * @return the value of article.primary_img
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public String getPrimaryImg() {
        return primaryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.primary_img
     *
     * @param primaryImg the value for article.primary_img
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setPrimaryImg(String primaryImg) {
        this.primaryImg = primaryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_type
     *
     * @return the value of article.article_type
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public Integer getArticleType() {
        return articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_type
     *
     * @param articleType the value for article.article_type
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setArticleType(Integer articleType) {
        this.articleType = articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.created_by_id
     *
     * @return the value of article.created_by_id
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public Integer getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.created_by_id
     *
     * @param createdById the value for article.created_by_id
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.created
     *
     * @return the value of article.created
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.created
     *
     * @param created the value for article.created
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updated_by_id
     *
     * @return the value of article.updated_by_id
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public Integer getUpdatedById() {
        return updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updated_by_id
     *
     * @param updatedById the value for article.updated_by_id
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setUpdatedById(Integer updatedById) {
        this.updatedById = updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updated
     *
     * @return the value of article.updated
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updated
     *
     * @param updated the value for article.updated
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updated
     *
     * @return the value of article.updated
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public String getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updated
     *
     * @param updated the value for article.updated
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    public void setCompleted(String completed) {
        this.completed = completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Article other = (Article) that;
        return (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getOutline() == null ? other.getOutline() == null : this.getOutline().equals(other.getOutline()))
            && (this.getContentFile() == null ? other.getContentFile() == null : this.getContentFile().equals(other.getContentFile()))
            && (this.getPrimaryImg() == null ? other.getPrimaryImg() == null : this.getPrimaryImg().equals(other.getPrimaryImg()))
            && (this.getArticleType() == null ? other.getArticleType() == null : this.getArticleType().equals(other.getArticleType()))
            && (this.getCreatedById() == null ? other.getCreatedById() == null : this.getCreatedById().equals(other.getCreatedById()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getUpdatedById() == null ? other.getUpdatedById() == null : this.getUpdatedById().equals(other.getUpdatedById()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getOutline() == null) ? 0 : getOutline().hashCode());
        result = prime * result + ((getContentFile() == null) ? 0 : getContentFile().hashCode());
        result = prime * result + ((getPrimaryImg() == null) ? 0 : getPrimaryImg().hashCode());
        result = prime * result + ((getArticleType() == null) ? 0 : getArticleType().hashCode());
        result = prime * result + ((getCreatedById() == null) ? 0 : getCreatedById().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getUpdatedById() == null) ? 0 : getUpdatedById().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sun May 16 08:20:36 EDT 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", title=").append(title);
        sb.append(", author=").append(author);
        sb.append(", source=").append(source);
        sb.append(", outline=").append(outline);
        sb.append(", contentFile=").append(contentFile);
        sb.append(", primaryImg=").append(primaryImg);
        sb.append(", articleType=").append(articleType);
        sb.append(", createdById=").append(createdById);
        sb.append(", created=").append(created);
        sb.append(", updatedById=").append(updatedById);
        sb.append(", updated=").append(updated);
        sb.append("]");
        return sb.toString();
    }
}