package com.empirestateids.domain;

import java.io.Serializable;
import java.util.Date;

public class Events implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_id
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    private Integer eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_date
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    private Date eventDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_desc
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    private String eventDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.coupon_code
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    private String couponCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table events
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_id
     *
     * @return the value of events.event_id
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_id
     *
     * @param eventId the value for events.event_id
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_date
     *
     * @return the value of events.event_date
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    public Date getEventDate() {
        return eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_date
     *
     * @param eventDate the value for events.event_date
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_desc
     *
     * @return the value of events.event_desc
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    public String getEventDesc() {
        return eventDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_desc
     *
     * @param eventDesc the value for events.event_desc
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    public void setEventDesc(String eventDesc) {
        this.eventDesc = eventDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.coupon_code
     *
     * @return the value of events.coupon_code
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    public String getCouponCode() {
        return couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.coupon_code
     *
     * @param couponCode the value for events.coupon_code
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Events other = (Events) that;
        return (this.getEventId() == null ? other.getEventId() == null : this.getEventId().equals(other.getEventId()))
            && (this.getEventDate() == null ? other.getEventDate() == null : this.getEventDate().equals(other.getEventDate()))
            && (this.getEventDesc() == null ? other.getEventDesc() == null : this.getEventDesc().equals(other.getEventDesc()))
            && (this.getCouponCode() == null ? other.getCouponCode() == null : this.getCouponCode().equals(other.getCouponCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEventId() == null) ? 0 : getEventId().hashCode());
        result = prime * result + ((getEventDate() == null) ? 0 : getEventDate().hashCode());
        result = prime * result + ((getEventDesc() == null) ? 0 : getEventDesc().hashCode());
        result = prime * result + ((getCouponCode() == null) ? 0 : getCouponCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sat Aug 11 11:14:34 EDT 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eventId=").append(eventId);
        sb.append(", eventDate=").append(eventDate);
        sb.append(", eventDesc=").append(eventDesc);
        sb.append(", couponCode=").append(couponCode);
        sb.append("]");
        return sb.toString();
    }
}