package com.empirestateids.domain;

import java.io.Serializable;
import java.util.Date;

public class Groups implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_name
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Integer createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.created
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Integer updatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.updated
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table groups
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_id
     *
     * @return the value of groups.group_id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_id
     *
     * @param groupId the value for groups.group_id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_name
     *
     * @return the value of groups.group_name
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_name
     *
     * @param groupName the value for groups.group_name
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.created_by_id
     *
     * @return the value of groups.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Integer getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.created_by_id
     *
     * @param createdById the value for groups.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.created
     *
     * @return the value of groups.created
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.created
     *
     * @param created the value for groups.created
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.updated_by_id
     *
     * @return the value of groups.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Integer getUpdatedById() {
        return updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.updated_by_id
     *
     * @param updatedById the value for groups.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setUpdatedById(Integer updatedById) {
        this.updatedById = updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.updated
     *
     * @return the value of groups.updated
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.updated
     *
     * @param updated the value for groups.updated
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Groups other = (Groups) that;
        return (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getGroupName() == null ? other.getGroupName() == null : this.getGroupName().equals(other.getGroupName()))
            && (this.getCreatedById() == null ? other.getCreatedById() == null : this.getCreatedById().equals(other.getCreatedById()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getUpdatedById() == null ? other.getUpdatedById() == null : this.getUpdatedById().equals(other.getUpdatedById()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getGroupName() == null) ? 0 : getGroupName().hashCode());
        result = prime * result + ((getCreatedById() == null) ? 0 : getCreatedById().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getUpdatedById() == null) ? 0 : getUpdatedById().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", groupName=").append(groupName);
        sb.append(", createdById=").append(createdById);
        sb.append(", created=").append(created);
        sb.append(", updatedById=").append(updatedById);
        sb.append(", updated=").append(updated);
        sb.append("]");
        return sb.toString();
    }
}