package com.empirestateids.domain;

import java.io.Serializable;
import java.util.Date;

public class GroupMember implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.group_member_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer groupMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.username
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.group_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.created
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer updatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.updated
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.group_member_id
     *
     * @return the value of group_member.group_member_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getGroupMemberId() {
        return groupMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.group_member_id
     *
     * @param groupMemberId the value for group_member.group_member_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setGroupMemberId(Integer groupMemberId) {
        this.groupMemberId = groupMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.username
     *
     * @return the value of group_member.username
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.username
     *
     * @param username the value for group_member.username
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.group_id
     *
     * @return the value of group_member.group_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.group_id
     *
     * @param groupId the value for group_member.group_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.created_by_id
     *
     * @return the value of group_member.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.created_by_id
     *
     * @param createdById the value for group_member.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.created
     *
     * @return the value of group_member.created
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.created
     *
     * @param created the value for group_member.created
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.updated_by_id
     *
     * @return the value of group_member.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getUpdatedById() {
        return updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.updated_by_id
     *
     * @param updatedById the value for group_member.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setUpdatedById(Integer updatedById) {
        this.updatedById = updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.updated
     *
     * @return the value of group_member.updated
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.updated
     *
     * @param updated the value for group_member.updated
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GroupMember other = (GroupMember) that;
        return (this.getGroupMemberId() == null ? other.getGroupMemberId() == null : this.getGroupMemberId().equals(other.getGroupMemberId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getCreatedById() == null ? other.getCreatedById() == null : this.getCreatedById().equals(other.getCreatedById()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getUpdatedById() == null ? other.getUpdatedById() == null : this.getUpdatedById().equals(other.getUpdatedById()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGroupMemberId() == null) ? 0 : getGroupMemberId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getCreatedById() == null) ? 0 : getCreatedById().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getUpdatedById() == null) ? 0 : getUpdatedById().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupMemberId=").append(groupMemberId);
        sb.append(", username=").append(username);
        sb.append(", groupId=").append(groupId);
        sb.append(", createdById=").append(createdById);
        sb.append(", created=").append(created);
        sb.append(", updatedById=").append(updatedById);
        sb.append(", updated=").append(updated);
        sb.append("]");
        return sb.toString();
    }
}