package com.empirestateids.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IpowerliftIdCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public IpowerliftIdCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIpowerliftIdIsNull() {
			addCriterion("ipowerlift_id is null");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdIsNotNull() {
			addCriterion("ipowerlift_id is not null");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdEqualTo(Integer value) {
			addCriterion("ipowerlift_id =", value, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdNotEqualTo(Integer value) {
			addCriterion("ipowerlift_id <>", value, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdGreaterThan(Integer value) {
			addCriterion("ipowerlift_id >", value, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ipowerlift_id >=", value, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdLessThan(Integer value) {
			addCriterion("ipowerlift_id <", value, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdLessThanOrEqualTo(Integer value) {
			addCriterion("ipowerlift_id <=", value, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdIn(List<Integer> values) {
			addCriterion("ipowerlift_id in", values, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdNotIn(List<Integer> values) {
			addCriterion("ipowerlift_id not in", values, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdBetween(Integer value1, Integer value2) {
			addCriterion("ipowerlift_id between", value1, value2, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andIpowerliftIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ipowerlift_id not between", value1, value2, "ipowerliftId");
			return (Criteria) this;
		}

		public Criteria andCreatedDateIsNull() {
			addCriterion("created_date is null");
			return (Criteria) this;
		}

		public Criteria andCreatedDateIsNotNull() {
			addCriterion("created_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedDateEqualTo(Date value) {
			addCriterion("created_date =", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateNotEqualTo(Date value) {
			addCriterion("created_date <>", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateGreaterThan(Date value) {
			addCriterion("created_date >", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("created_date >=", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateLessThan(Date value) {
			addCriterion("created_date <", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
			addCriterion("created_date <=", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateIn(List<Date> values) {
			addCriterion("created_date in", values, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateNotIn(List<Date> values) {
			addCriterion("created_date not in", values, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateBetween(Date value1, Date value2) {
			addCriterion("created_date between", value1, value2, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
			addCriterion("created_date not between", value1, value2, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedIdIsNull() {
			addCriterion("created_id is null");
			return (Criteria) this;
		}

		public Criteria andCreatedIdIsNotNull() {
			addCriterion("created_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedIdEqualTo(Integer value) {
			addCriterion("created_id =", value, "createdId");
			return (Criteria) this;
		}

		public Criteria andCreatedIdNotEqualTo(Integer value) {
			addCriterion("created_id <>", value, "createdId");
			return (Criteria) this;
		}

		public Criteria andCreatedIdGreaterThan(Integer value) {
			addCriterion("created_id >", value, "createdId");
			return (Criteria) this;
		}

		public Criteria andCreatedIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("created_id >=", value, "createdId");
			return (Criteria) this;
		}

		public Criteria andCreatedIdLessThan(Integer value) {
			addCriterion("created_id <", value, "createdId");
			return (Criteria) this;
		}

		public Criteria andCreatedIdLessThanOrEqualTo(Integer value) {
			addCriterion("created_id <=", value, "createdId");
			return (Criteria) this;
		}

		public Criteria andCreatedIdIn(List<Integer> values) {
			addCriterion("created_id in", values, "createdId");
			return (Criteria) this;
		}

		public Criteria andCreatedIdNotIn(List<Integer> values) {
			addCriterion("created_id not in", values, "createdId");
			return (Criteria) this;
		}

		public Criteria andCreatedIdBetween(Integer value1, Integer value2) {
			addCriterion("created_id between", value1, value2, "createdId");
			return (Criteria) this;
		}

		public Criteria andCreatedIdNotBetween(Integer value1, Integer value2) {
			addCriterion("created_id not between", value1, value2, "createdId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ipowerlift_id
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 12 16:37:22 EDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}