package com.empirestateids.domain;

import java.io.Serializable;
import java.util.Date;

public class IpowerliftId implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ipowerlift_id.ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	private Integer ipowerliftId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ipowerlift_id.created_date
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ipowerlift_id.created_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	private Integer createdId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ipowerlift_id.ipowerlift_id
	 * @return  the value of ipowerlift_id.ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public Integer getIpowerliftId() {
		return ipowerliftId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ipowerlift_id.ipowerlift_id
	 * @param ipowerliftId  the value for ipowerlift_id.ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public void setIpowerliftId(Integer ipowerliftId) {
		this.ipowerliftId = ipowerliftId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ipowerlift_id.created_date
	 * @return  the value of ipowerlift_id.created_date
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ipowerlift_id.created_date
	 * @param createdDate  the value for ipowerlift_id.created_date
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ipowerlift_id.created_id
	 * @return  the value of ipowerlift_id.created_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public Integer getCreatedId() {
		return createdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ipowerlift_id.created_id
	 * @param createdId  the value for ipowerlift_id.created_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	public void setCreatedId(Integer createdId) {
		this.createdId = createdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		IpowerliftId other = (IpowerliftId) that;
		return (this.getIpowerliftId() == null ? other.getIpowerliftId() == null
				: this.getIpowerliftId().equals(other.getIpowerliftId()))
				&& (this.getCreatedDate() == null ? other.getCreatedDate() == null
						: this.getCreatedDate().equals(other.getCreatedDate()))
				&& (this.getCreatedId() == null ? other.getCreatedId() == null
						: this.getCreatedId().equals(other.getCreatedId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getIpowerliftId() == null) ? 0 : getIpowerliftId().hashCode());
		result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
		result = prime * result + ((getCreatedId() == null) ? 0 : getCreatedId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", ipowerliftId=").append(ipowerliftId);
		sb.append(", createdDate=").append(createdDate);
		sb.append(", createdId=").append(createdId);
		sb.append("]");
		return sb.toString();
	}
}