package com.empirestateids.domain;

import java.util.ArrayList;
import java.util.List;

public class LoincExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public LoincExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLoincNumIsNull() {
			addCriterion("LOINC_NUM is null");
			return (Criteria) this;
		}

		public Criteria andLoincNumIsNotNull() {
			addCriterion("LOINC_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andLoincNumEqualTo(String value) {
			addCriterion("LOINC_NUM =", value, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumNotEqualTo(String value) {
			addCriterion("LOINC_NUM <>", value, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumGreaterThan(String value) {
			addCriterion("LOINC_NUM >", value, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumGreaterThanOrEqualTo(String value) {
			addCriterion("LOINC_NUM >=", value, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumLessThan(String value) {
			addCriterion("LOINC_NUM <", value, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumLessThanOrEqualTo(String value) {
			addCriterion("LOINC_NUM <=", value, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumLike(String value) {
			addCriterion("LOINC_NUM like", value, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumNotLike(String value) {
			addCriterion("LOINC_NUM not like", value, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumIn(List<String> values) {
			addCriterion("LOINC_NUM in", values, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumNotIn(List<String> values) {
			addCriterion("LOINC_NUM not in", values, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumBetween(String value1, String value2) {
			addCriterion("LOINC_NUM between", value1, value2, "loincNum");
			return (Criteria) this;
		}

		public Criteria andLoincNumNotBetween(String value1, String value2) {
			addCriterion("LOINC_NUM not between", value1, value2, "loincNum");
			return (Criteria) this;
		}

		public Criteria andComponentIsNull() {
			addCriterion("COMPONENT is null");
			return (Criteria) this;
		}

		public Criteria andComponentIsNotNull() {
			addCriterion("COMPONENT is not null");
			return (Criteria) this;
		}

		public Criteria andComponentEqualTo(String value) {
			addCriterion("COMPONENT =", value, "component");
			return (Criteria) this;
		}

		public Criteria andComponentNotEqualTo(String value) {
			addCriterion("COMPONENT <>", value, "component");
			return (Criteria) this;
		}

		public Criteria andComponentGreaterThan(String value) {
			addCriterion("COMPONENT >", value, "component");
			return (Criteria) this;
		}

		public Criteria andComponentGreaterThanOrEqualTo(String value) {
			addCriterion("COMPONENT >=", value, "component");
			return (Criteria) this;
		}

		public Criteria andComponentLessThan(String value) {
			addCriterion("COMPONENT <", value, "component");
			return (Criteria) this;
		}

		public Criteria andComponentLessThanOrEqualTo(String value) {
			addCriterion("COMPONENT <=", value, "component");
			return (Criteria) this;
		}

		public Criteria andComponentLike(String value) {
			addCriterion("COMPONENT like", value, "component");
			return (Criteria) this;
		}

		public Criteria andComponentNotLike(String value) {
			addCriterion("COMPONENT not like", value, "component");
			return (Criteria) this;
		}

		public Criteria andComponentIn(List<String> values) {
			addCriterion("COMPONENT in", values, "component");
			return (Criteria) this;
		}

		public Criteria andComponentNotIn(List<String> values) {
			addCriterion("COMPONENT not in", values, "component");
			return (Criteria) this;
		}

		public Criteria andComponentBetween(String value1, String value2) {
			addCriterion("COMPONENT between", value1, value2, "component");
			return (Criteria) this;
		}

		public Criteria andComponentNotBetween(String value1, String value2) {
			addCriterion("COMPONENT not between", value1, value2, "component");
			return (Criteria) this;
		}

		public Criteria andPropertyIsNull() {
			addCriterion("PROPERTY is null");
			return (Criteria) this;
		}

		public Criteria andPropertyIsNotNull() {
			addCriterion("PROPERTY is not null");
			return (Criteria) this;
		}

		public Criteria andPropertyEqualTo(String value) {
			addCriterion("PROPERTY =", value, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyNotEqualTo(String value) {
			addCriterion("PROPERTY <>", value, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyGreaterThan(String value) {
			addCriterion("PROPERTY >", value, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyGreaterThanOrEqualTo(String value) {
			addCriterion("PROPERTY >=", value, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyLessThan(String value) {
			addCriterion("PROPERTY <", value, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyLessThanOrEqualTo(String value) {
			addCriterion("PROPERTY <=", value, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyLike(String value) {
			addCriterion("PROPERTY like", value, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyNotLike(String value) {
			addCriterion("PROPERTY not like", value, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyIn(List<String> values) {
			addCriterion("PROPERTY in", values, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyNotIn(List<String> values) {
			addCriterion("PROPERTY not in", values, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyBetween(String value1, String value2) {
			addCriterion("PROPERTY between", value1, value2, "property");
			return (Criteria) this;
		}

		public Criteria andPropertyNotBetween(String value1, String value2) {
			addCriterion("PROPERTY not between", value1, value2, "property");
			return (Criteria) this;
		}

		public Criteria andTimeAspctIsNull() {
			addCriterion("TIME_ASPCT is null");
			return (Criteria) this;
		}

		public Criteria andTimeAspctIsNotNull() {
			addCriterion("TIME_ASPCT is not null");
			return (Criteria) this;
		}

		public Criteria andTimeAspctEqualTo(String value) {
			addCriterion("TIME_ASPCT =", value, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctNotEqualTo(String value) {
			addCriterion("TIME_ASPCT <>", value, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctGreaterThan(String value) {
			addCriterion("TIME_ASPCT >", value, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctGreaterThanOrEqualTo(String value) {
			addCriterion("TIME_ASPCT >=", value, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctLessThan(String value) {
			addCriterion("TIME_ASPCT <", value, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctLessThanOrEqualTo(String value) {
			addCriterion("TIME_ASPCT <=", value, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctLike(String value) {
			addCriterion("TIME_ASPCT like", value, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctNotLike(String value) {
			addCriterion("TIME_ASPCT not like", value, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctIn(List<String> values) {
			addCriterion("TIME_ASPCT in", values, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctNotIn(List<String> values) {
			addCriterion("TIME_ASPCT not in", values, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctBetween(String value1, String value2) {
			addCriterion("TIME_ASPCT between", value1, value2, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andTimeAspctNotBetween(String value1, String value2) {
			addCriterion("TIME_ASPCT not between", value1, value2, "timeAspct");
			return (Criteria) this;
		}

		public Criteria andSystemIsNull() {
			addCriterion("SYSTEM is null");
			return (Criteria) this;
		}

		public Criteria andSystemIsNotNull() {
			addCriterion("SYSTEM is not null");
			return (Criteria) this;
		}

		public Criteria andSystemEqualTo(String value) {
			addCriterion("SYSTEM =", value, "system");
			return (Criteria) this;
		}

		public Criteria andSystemNotEqualTo(String value) {
			addCriterion("SYSTEM <>", value, "system");
			return (Criteria) this;
		}

		public Criteria andSystemGreaterThan(String value) {
			addCriterion("SYSTEM >", value, "system");
			return (Criteria) this;
		}

		public Criteria andSystemGreaterThanOrEqualTo(String value) {
			addCriterion("SYSTEM >=", value, "system");
			return (Criteria) this;
		}

		public Criteria andSystemLessThan(String value) {
			addCriterion("SYSTEM <", value, "system");
			return (Criteria) this;
		}

		public Criteria andSystemLessThanOrEqualTo(String value) {
			addCriterion("SYSTEM <=", value, "system");
			return (Criteria) this;
		}

		public Criteria andSystemLike(String value) {
			addCriterion("SYSTEM like", value, "system");
			return (Criteria) this;
		}

		public Criteria andSystemNotLike(String value) {
			addCriterion("SYSTEM not like", value, "system");
			return (Criteria) this;
		}

		public Criteria andSystemIn(List<String> values) {
			addCriterion("SYSTEM in", values, "system");
			return (Criteria) this;
		}

		public Criteria andSystemNotIn(List<String> values) {
			addCriterion("SYSTEM not in", values, "system");
			return (Criteria) this;
		}

		public Criteria andSystemBetween(String value1, String value2) {
			addCriterion("SYSTEM between", value1, value2, "system");
			return (Criteria) this;
		}

		public Criteria andSystemNotBetween(String value1, String value2) {
			addCriterion("SYSTEM not between", value1, value2, "system");
			return (Criteria) this;
		}

		public Criteria andScaleTypIsNull() {
			addCriterion("SCALE_TYP is null");
			return (Criteria) this;
		}

		public Criteria andScaleTypIsNotNull() {
			addCriterion("SCALE_TYP is not null");
			return (Criteria) this;
		}

		public Criteria andScaleTypEqualTo(String value) {
			addCriterion("SCALE_TYP =", value, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypNotEqualTo(String value) {
			addCriterion("SCALE_TYP <>", value, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypGreaterThan(String value) {
			addCriterion("SCALE_TYP >", value, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypGreaterThanOrEqualTo(String value) {
			addCriterion("SCALE_TYP >=", value, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypLessThan(String value) {
			addCriterion("SCALE_TYP <", value, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypLessThanOrEqualTo(String value) {
			addCriterion("SCALE_TYP <=", value, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypLike(String value) {
			addCriterion("SCALE_TYP like", value, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypNotLike(String value) {
			addCriterion("SCALE_TYP not like", value, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypIn(List<String> values) {
			addCriterion("SCALE_TYP in", values, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypNotIn(List<String> values) {
			addCriterion("SCALE_TYP not in", values, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypBetween(String value1, String value2) {
			addCriterion("SCALE_TYP between", value1, value2, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andScaleTypNotBetween(String value1, String value2) {
			addCriterion("SCALE_TYP not between", value1, value2, "scaleTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypIsNull() {
			addCriterion("METHOD_TYP is null");
			return (Criteria) this;
		}

		public Criteria andMethodTypIsNotNull() {
			addCriterion("METHOD_TYP is not null");
			return (Criteria) this;
		}

		public Criteria andMethodTypEqualTo(String value) {
			addCriterion("METHOD_TYP =", value, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypNotEqualTo(String value) {
			addCriterion("METHOD_TYP <>", value, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypGreaterThan(String value) {
			addCriterion("METHOD_TYP >", value, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypGreaterThanOrEqualTo(String value) {
			addCriterion("METHOD_TYP >=", value, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypLessThan(String value) {
			addCriterion("METHOD_TYP <", value, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypLessThanOrEqualTo(String value) {
			addCriterion("METHOD_TYP <=", value, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypLike(String value) {
			addCriterion("METHOD_TYP like", value, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypNotLike(String value) {
			addCriterion("METHOD_TYP not like", value, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypIn(List<String> values) {
			addCriterion("METHOD_TYP in", values, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypNotIn(List<String> values) {
			addCriterion("METHOD_TYP not in", values, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypBetween(String value1, String value2) {
			addCriterion("METHOD_TYP between", value1, value2, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andMethodTypNotBetween(String value1, String value2) {
			addCriterion("METHOD_TYP not between", value1, value2, "methodTyp");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNull() {
			addCriterion("CLASS_NAME is null");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNotNull() {
			addCriterion("CLASS_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andClassNameEqualTo(String value) {
			addCriterion("CLASS_NAME =", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotEqualTo(String value) {
			addCriterion("CLASS_NAME <>", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThan(String value) {
			addCriterion("CLASS_NAME >", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThanOrEqualTo(String value) {
			addCriterion("CLASS_NAME >=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThan(String value) {
			addCriterion("CLASS_NAME <", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThanOrEqualTo(String value) {
			addCriterion("CLASS_NAME <=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLike(String value) {
			addCriterion("CLASS_NAME like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotLike(String value) {
			addCriterion("CLASS_NAME not like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameIn(List<String> values) {
			addCriterion("CLASS_NAME in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotIn(List<String> values) {
			addCriterion("CLASS_NAME not in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameBetween(String value1, String value2) {
			addCriterion("CLASS_NAME between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotBetween(String value1, String value2) {
			addCriterion("CLASS_NAME not between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedIsNull() {
			addCriterion("VersionLastChanged is null");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedIsNotNull() {
			addCriterion("VersionLastChanged is not null");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedEqualTo(String value) {
			addCriterion("VersionLastChanged =", value, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedNotEqualTo(String value) {
			addCriterion("VersionLastChanged <>", value, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedGreaterThan(String value) {
			addCriterion("VersionLastChanged >", value, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedGreaterThanOrEqualTo(String value) {
			addCriterion("VersionLastChanged >=", value, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedLessThan(String value) {
			addCriterion("VersionLastChanged <", value, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedLessThanOrEqualTo(String value) {
			addCriterion("VersionLastChanged <=", value, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedLike(String value) {
			addCriterion("VersionLastChanged like", value, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedNotLike(String value) {
			addCriterion("VersionLastChanged not like", value, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedIn(List<String> values) {
			addCriterion("VersionLastChanged in", values, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedNotIn(List<String> values) {
			addCriterion("VersionLastChanged not in", values, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedBetween(String value1, String value2) {
			addCriterion("VersionLastChanged between", value1, value2, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andVersionlastchangedNotBetween(String value1, String value2) {
			addCriterion("VersionLastChanged not between", value1, value2, "versionlastchanged");
			return (Criteria) this;
		}

		public Criteria andChngTypeIsNull() {
			addCriterion("CHNG_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andChngTypeIsNotNull() {
			addCriterion("CHNG_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andChngTypeEqualTo(String value) {
			addCriterion("CHNG_TYPE =", value, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeNotEqualTo(String value) {
			addCriterion("CHNG_TYPE <>", value, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeGreaterThan(String value) {
			addCriterion("CHNG_TYPE >", value, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeGreaterThanOrEqualTo(String value) {
			addCriterion("CHNG_TYPE >=", value, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeLessThan(String value) {
			addCriterion("CHNG_TYPE <", value, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeLessThanOrEqualTo(String value) {
			addCriterion("CHNG_TYPE <=", value, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeLike(String value) {
			addCriterion("CHNG_TYPE like", value, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeNotLike(String value) {
			addCriterion("CHNG_TYPE not like", value, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeIn(List<String> values) {
			addCriterion("CHNG_TYPE in", values, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeNotIn(List<String> values) {
			addCriterion("CHNG_TYPE not in", values, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeBetween(String value1, String value2) {
			addCriterion("CHNG_TYPE between", value1, value2, "chngType");
			return (Criteria) this;
		}

		public Criteria andChngTypeNotBetween(String value1, String value2) {
			addCriterion("CHNG_TYPE not between", value1, value2, "chngType");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionIsNull() {
			addCriterion("DefinitionDescription is null");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionIsNotNull() {
			addCriterion("DefinitionDescription is not null");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionEqualTo(String value) {
			addCriterion("DefinitionDescription =", value, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionNotEqualTo(String value) {
			addCriterion("DefinitionDescription <>", value, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionGreaterThan(String value) {
			addCriterion("DefinitionDescription >", value, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DefinitionDescription >=", value, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionLessThan(String value) {
			addCriterion("DefinitionDescription <", value, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionLessThanOrEqualTo(String value) {
			addCriterion("DefinitionDescription <=", value, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionLike(String value) {
			addCriterion("DefinitionDescription like", value, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionNotLike(String value) {
			addCriterion("DefinitionDescription not like", value, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionIn(List<String> values) {
			addCriterion("DefinitionDescription in", values, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionNotIn(List<String> values) {
			addCriterion("DefinitionDescription not in", values, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionBetween(String value1, String value2) {
			addCriterion("DefinitionDescription between", value1, value2, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andDefinitiondescriptionNotBetween(String value1, String value2) {
			addCriterion("DefinitionDescription not between", value1, value2, "definitiondescription");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andConsumerNameIsNull() {
			addCriterion("CONSUMER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andConsumerNameIsNotNull() {
			addCriterion("CONSUMER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andConsumerNameEqualTo(String value) {
			addCriterion("CONSUMER_NAME =", value, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameNotEqualTo(String value) {
			addCriterion("CONSUMER_NAME <>", value, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameGreaterThan(String value) {
			addCriterion("CONSUMER_NAME >", value, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameGreaterThanOrEqualTo(String value) {
			addCriterion("CONSUMER_NAME >=", value, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameLessThan(String value) {
			addCriterion("CONSUMER_NAME <", value, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameLessThanOrEqualTo(String value) {
			addCriterion("CONSUMER_NAME <=", value, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameLike(String value) {
			addCriterion("CONSUMER_NAME like", value, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameNotLike(String value) {
			addCriterion("CONSUMER_NAME not like", value, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameIn(List<String> values) {
			addCriterion("CONSUMER_NAME in", values, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameNotIn(List<String> values) {
			addCriterion("CONSUMER_NAME not in", values, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameBetween(String value1, String value2) {
			addCriterion("CONSUMER_NAME between", value1, value2, "consumerName");
			return (Criteria) this;
		}

		public Criteria andConsumerNameNotBetween(String value1, String value2) {
			addCriterion("CONSUMER_NAME not between", value1, value2, "consumerName");
			return (Criteria) this;
		}

		public Criteria andClasstypeIsNull() {
			addCriterion("CLASSTYPE is null");
			return (Criteria) this;
		}

		public Criteria andClasstypeIsNotNull() {
			addCriterion("CLASSTYPE is not null");
			return (Criteria) this;
		}

		public Criteria andClasstypeEqualTo(Integer value) {
			addCriterion("CLASSTYPE =", value, "classtype");
			return (Criteria) this;
		}

		public Criteria andClasstypeNotEqualTo(Integer value) {
			addCriterion("CLASSTYPE <>", value, "classtype");
			return (Criteria) this;
		}

		public Criteria andClasstypeGreaterThan(Integer value) {
			addCriterion("CLASSTYPE >", value, "classtype");
			return (Criteria) this;
		}

		public Criteria andClasstypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("CLASSTYPE >=", value, "classtype");
			return (Criteria) this;
		}

		public Criteria andClasstypeLessThan(Integer value) {
			addCriterion("CLASSTYPE <", value, "classtype");
			return (Criteria) this;
		}

		public Criteria andClasstypeLessThanOrEqualTo(Integer value) {
			addCriterion("CLASSTYPE <=", value, "classtype");
			return (Criteria) this;
		}

		public Criteria andClasstypeIn(List<Integer> values) {
			addCriterion("CLASSTYPE in", values, "classtype");
			return (Criteria) this;
		}

		public Criteria andClasstypeNotIn(List<Integer> values) {
			addCriterion("CLASSTYPE not in", values, "classtype");
			return (Criteria) this;
		}

		public Criteria andClasstypeBetween(Integer value1, Integer value2) {
			addCriterion("CLASSTYPE between", value1, value2, "classtype");
			return (Criteria) this;
		}

		public Criteria andClasstypeNotBetween(Integer value1, Integer value2) {
			addCriterion("CLASSTYPE not between", value1, value2, "classtype");
			return (Criteria) this;
		}

		public Criteria andFormulaIsNull() {
			addCriterion("FORMULA is null");
			return (Criteria) this;
		}

		public Criteria andFormulaIsNotNull() {
			addCriterion("FORMULA is not null");
			return (Criteria) this;
		}

		public Criteria andFormulaEqualTo(String value) {
			addCriterion("FORMULA =", value, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaNotEqualTo(String value) {
			addCriterion("FORMULA <>", value, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaGreaterThan(String value) {
			addCriterion("FORMULA >", value, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaGreaterThanOrEqualTo(String value) {
			addCriterion("FORMULA >=", value, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaLessThan(String value) {
			addCriterion("FORMULA <", value, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaLessThanOrEqualTo(String value) {
			addCriterion("FORMULA <=", value, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaLike(String value) {
			addCriterion("FORMULA like", value, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaNotLike(String value) {
			addCriterion("FORMULA not like", value, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaIn(List<String> values) {
			addCriterion("FORMULA in", values, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaNotIn(List<String> values) {
			addCriterion("FORMULA not in", values, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaBetween(String value1, String value2) {
			addCriterion("FORMULA between", value1, value2, "formula");
			return (Criteria) this;
		}

		public Criteria andFormulaNotBetween(String value1, String value2) {
			addCriterion("FORMULA not between", value1, value2, "formula");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersIsNull() {
			addCriterion("EXMPL_ANSWERS is null");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersIsNotNull() {
			addCriterion("EXMPL_ANSWERS is not null");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersEqualTo(String value) {
			addCriterion("EXMPL_ANSWERS =", value, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersNotEqualTo(String value) {
			addCriterion("EXMPL_ANSWERS <>", value, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersGreaterThan(String value) {
			addCriterion("EXMPL_ANSWERS >", value, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersGreaterThanOrEqualTo(String value) {
			addCriterion("EXMPL_ANSWERS >=", value, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersLessThan(String value) {
			addCriterion("EXMPL_ANSWERS <", value, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersLessThanOrEqualTo(String value) {
			addCriterion("EXMPL_ANSWERS <=", value, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersLike(String value) {
			addCriterion("EXMPL_ANSWERS like", value, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersNotLike(String value) {
			addCriterion("EXMPL_ANSWERS not like", value, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersIn(List<String> values) {
			addCriterion("EXMPL_ANSWERS in", values, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersNotIn(List<String> values) {
			addCriterion("EXMPL_ANSWERS not in", values, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersBetween(String value1, String value2) {
			addCriterion("EXMPL_ANSWERS between", value1, value2, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andExmplAnswersNotBetween(String value1, String value2) {
			addCriterion("EXMPL_ANSWERS not between", value1, value2, "exmplAnswers");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextIsNull() {
			addCriterion("SURVEY_QUEST_TEXT is null");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextIsNotNull() {
			addCriterion("SURVEY_QUEST_TEXT is not null");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextEqualTo(String value) {
			addCriterion("SURVEY_QUEST_TEXT =", value, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextNotEqualTo(String value) {
			addCriterion("SURVEY_QUEST_TEXT <>", value, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextGreaterThan(String value) {
			addCriterion("SURVEY_QUEST_TEXT >", value, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextGreaterThanOrEqualTo(String value) {
			addCriterion("SURVEY_QUEST_TEXT >=", value, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextLessThan(String value) {
			addCriterion("SURVEY_QUEST_TEXT <", value, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextLessThanOrEqualTo(String value) {
			addCriterion("SURVEY_QUEST_TEXT <=", value, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextLike(String value) {
			addCriterion("SURVEY_QUEST_TEXT like", value, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextNotLike(String value) {
			addCriterion("SURVEY_QUEST_TEXT not like", value, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextIn(List<String> values) {
			addCriterion("SURVEY_QUEST_TEXT in", values, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextNotIn(List<String> values) {
			addCriterion("SURVEY_QUEST_TEXT not in", values, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextBetween(String value1, String value2) {
			addCriterion("SURVEY_QUEST_TEXT between", value1, value2, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestTextNotBetween(String value1, String value2) {
			addCriterion("SURVEY_QUEST_TEXT not between", value1, value2, "surveyQuestText");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcIsNull() {
			addCriterion("SURVEY_QUEST_SRC is null");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcIsNotNull() {
			addCriterion("SURVEY_QUEST_SRC is not null");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcEqualTo(String value) {
			addCriterion("SURVEY_QUEST_SRC =", value, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcNotEqualTo(String value) {
			addCriterion("SURVEY_QUEST_SRC <>", value, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcGreaterThan(String value) {
			addCriterion("SURVEY_QUEST_SRC >", value, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcGreaterThanOrEqualTo(String value) {
			addCriterion("SURVEY_QUEST_SRC >=", value, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcLessThan(String value) {
			addCriterion("SURVEY_QUEST_SRC <", value, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcLessThanOrEqualTo(String value) {
			addCriterion("SURVEY_QUEST_SRC <=", value, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcLike(String value) {
			addCriterion("SURVEY_QUEST_SRC like", value, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcNotLike(String value) {
			addCriterion("SURVEY_QUEST_SRC not like", value, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcIn(List<String> values) {
			addCriterion("SURVEY_QUEST_SRC in", values, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcNotIn(List<String> values) {
			addCriterion("SURVEY_QUEST_SRC not in", values, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcBetween(String value1, String value2) {
			addCriterion("SURVEY_QUEST_SRC between", value1, value2, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andSurveyQuestSrcNotBetween(String value1, String value2) {
			addCriterion("SURVEY_QUEST_SRC not between", value1, value2, "surveyQuestSrc");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredIsNull() {
			addCriterion("UNITSREQUIRED is null");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredIsNotNull() {
			addCriterion("UNITSREQUIRED is not null");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredEqualTo(String value) {
			addCriterion("UNITSREQUIRED =", value, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredNotEqualTo(String value) {
			addCriterion("UNITSREQUIRED <>", value, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredGreaterThan(String value) {
			addCriterion("UNITSREQUIRED >", value, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredGreaterThanOrEqualTo(String value) {
			addCriterion("UNITSREQUIRED >=", value, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredLessThan(String value) {
			addCriterion("UNITSREQUIRED <", value, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredLessThanOrEqualTo(String value) {
			addCriterion("UNITSREQUIRED <=", value, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredLike(String value) {
			addCriterion("UNITSREQUIRED like", value, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredNotLike(String value) {
			addCriterion("UNITSREQUIRED not like", value, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredIn(List<String> values) {
			addCriterion("UNITSREQUIRED in", values, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredNotIn(List<String> values) {
			addCriterion("UNITSREQUIRED not in", values, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredBetween(String value1, String value2) {
			addCriterion("UNITSREQUIRED between", value1, value2, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andUnitsrequiredNotBetween(String value1, String value2) {
			addCriterion("UNITSREQUIRED not between", value1, value2, "unitsrequired");
			return (Criteria) this;
		}

		public Criteria andRelatednames2IsNull() {
			addCriterion("RELATEDNAMES2 is null");
			return (Criteria) this;
		}

		public Criteria andRelatednames2IsNotNull() {
			addCriterion("RELATEDNAMES2 is not null");
			return (Criteria) this;
		}

		public Criteria andRelatednames2EqualTo(String value) {
			addCriterion("RELATEDNAMES2 =", value, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2NotEqualTo(String value) {
			addCriterion("RELATEDNAMES2 <>", value, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2GreaterThan(String value) {
			addCriterion("RELATEDNAMES2 >", value, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2GreaterThanOrEqualTo(String value) {
			addCriterion("RELATEDNAMES2 >=", value, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2LessThan(String value) {
			addCriterion("RELATEDNAMES2 <", value, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2LessThanOrEqualTo(String value) {
			addCriterion("RELATEDNAMES2 <=", value, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2Like(String value) {
			addCriterion("RELATEDNAMES2 like", value, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2NotLike(String value) {
			addCriterion("RELATEDNAMES2 not like", value, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2In(List<String> values) {
			addCriterion("RELATEDNAMES2 in", values, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2NotIn(List<String> values) {
			addCriterion("RELATEDNAMES2 not in", values, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2Between(String value1, String value2) {
			addCriterion("RELATEDNAMES2 between", value1, value2, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andRelatednames2NotBetween(String value1, String value2) {
			addCriterion("RELATEDNAMES2 not between", value1, value2, "relatednames2");
			return (Criteria) this;
		}

		public Criteria andShortnameIsNull() {
			addCriterion("SHORTNAME is null");
			return (Criteria) this;
		}

		public Criteria andShortnameIsNotNull() {
			addCriterion("SHORTNAME is not null");
			return (Criteria) this;
		}

		public Criteria andShortnameEqualTo(String value) {
			addCriterion("SHORTNAME =", value, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameNotEqualTo(String value) {
			addCriterion("SHORTNAME <>", value, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameGreaterThan(String value) {
			addCriterion("SHORTNAME >", value, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameGreaterThanOrEqualTo(String value) {
			addCriterion("SHORTNAME >=", value, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameLessThan(String value) {
			addCriterion("SHORTNAME <", value, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameLessThanOrEqualTo(String value) {
			addCriterion("SHORTNAME <=", value, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameLike(String value) {
			addCriterion("SHORTNAME like", value, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameNotLike(String value) {
			addCriterion("SHORTNAME not like", value, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameIn(List<String> values) {
			addCriterion("SHORTNAME in", values, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameNotIn(List<String> values) {
			addCriterion("SHORTNAME not in", values, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameBetween(String value1, String value2) {
			addCriterion("SHORTNAME between", value1, value2, "shortname");
			return (Criteria) this;
		}

		public Criteria andShortnameNotBetween(String value1, String value2) {
			addCriterion("SHORTNAME not between", value1, value2, "shortname");
			return (Criteria) this;
		}

		public Criteria andOrderObsIsNull() {
			addCriterion("ORDER_OBS is null");
			return (Criteria) this;
		}

		public Criteria andOrderObsIsNotNull() {
			addCriterion("ORDER_OBS is not null");
			return (Criteria) this;
		}

		public Criteria andOrderObsEqualTo(String value) {
			addCriterion("ORDER_OBS =", value, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsNotEqualTo(String value) {
			addCriterion("ORDER_OBS <>", value, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsGreaterThan(String value) {
			addCriterion("ORDER_OBS >", value, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_OBS >=", value, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsLessThan(String value) {
			addCriterion("ORDER_OBS <", value, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsLessThanOrEqualTo(String value) {
			addCriterion("ORDER_OBS <=", value, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsLike(String value) {
			addCriterion("ORDER_OBS like", value, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsNotLike(String value) {
			addCriterion("ORDER_OBS not like", value, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsIn(List<String> values) {
			addCriterion("ORDER_OBS in", values, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsNotIn(List<String> values) {
			addCriterion("ORDER_OBS not in", values, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsBetween(String value1, String value2) {
			addCriterion("ORDER_OBS between", value1, value2, "orderObs");
			return (Criteria) this;
		}

		public Criteria andOrderObsNotBetween(String value1, String value2) {
			addCriterion("ORDER_OBS not between", value1, value2, "orderObs");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdIsNull() {
			addCriterion("HL7_FIELD_SUBFIELD_ID is null");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdIsNotNull() {
			addCriterion("HL7_FIELD_SUBFIELD_ID is not null");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdEqualTo(String value) {
			addCriterion("HL7_FIELD_SUBFIELD_ID =", value, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdNotEqualTo(String value) {
			addCriterion("HL7_FIELD_SUBFIELD_ID <>", value, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdGreaterThan(String value) {
			addCriterion("HL7_FIELD_SUBFIELD_ID >", value, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdGreaterThanOrEqualTo(String value) {
			addCriterion("HL7_FIELD_SUBFIELD_ID >=", value, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdLessThan(String value) {
			addCriterion("HL7_FIELD_SUBFIELD_ID <", value, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdLessThanOrEqualTo(String value) {
			addCriterion("HL7_FIELD_SUBFIELD_ID <=", value, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdLike(String value) {
			addCriterion("HL7_FIELD_SUBFIELD_ID like", value, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdNotLike(String value) {
			addCriterion("HL7_FIELD_SUBFIELD_ID not like", value, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdIn(List<String> values) {
			addCriterion("HL7_FIELD_SUBFIELD_ID in", values, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdNotIn(List<String> values) {
			addCriterion("HL7_FIELD_SUBFIELD_ID not in", values, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdBetween(String value1, String value2) {
			addCriterion("HL7_FIELD_SUBFIELD_ID between", value1, value2, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andHl7FieldSubfieldIdNotBetween(String value1, String value2) {
			addCriterion("HL7_FIELD_SUBFIELD_ID not between", value1, value2, "hl7FieldSubfieldId");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsIsNull() {
			addCriterion("EXAMPLE_UNITS is null");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsIsNotNull() {
			addCriterion("EXAMPLE_UNITS is not null");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsEqualTo(String value) {
			addCriterion("EXAMPLE_UNITS =", value, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsNotEqualTo(String value) {
			addCriterion("EXAMPLE_UNITS <>", value, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsGreaterThan(String value) {
			addCriterion("EXAMPLE_UNITS >", value, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsGreaterThanOrEqualTo(String value) {
			addCriterion("EXAMPLE_UNITS >=", value, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsLessThan(String value) {
			addCriterion("EXAMPLE_UNITS <", value, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsLessThanOrEqualTo(String value) {
			addCriterion("EXAMPLE_UNITS <=", value, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsLike(String value) {
			addCriterion("EXAMPLE_UNITS like", value, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsNotLike(String value) {
			addCriterion("EXAMPLE_UNITS not like", value, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsIn(List<String> values) {
			addCriterion("EXAMPLE_UNITS in", values, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsNotIn(List<String> values) {
			addCriterion("EXAMPLE_UNITS not in", values, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsBetween(String value1, String value2) {
			addCriterion("EXAMPLE_UNITS between", value1, value2, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUnitsNotBetween(String value1, String value2) {
			addCriterion("EXAMPLE_UNITS not between", value1, value2, "exampleUnits");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameIsNull() {
			addCriterion("LONG_COMMON_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameIsNotNull() {
			addCriterion("LONG_COMMON_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameEqualTo(String value) {
			addCriterion("LONG_COMMON_NAME =", value, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameNotEqualTo(String value) {
			addCriterion("LONG_COMMON_NAME <>", value, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameGreaterThan(String value) {
			addCriterion("LONG_COMMON_NAME >", value, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameGreaterThanOrEqualTo(String value) {
			addCriterion("LONG_COMMON_NAME >=", value, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameLessThan(String value) {
			addCriterion("LONG_COMMON_NAME <", value, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameLessThanOrEqualTo(String value) {
			addCriterion("LONG_COMMON_NAME <=", value, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameLike(String value) {
			addCriterion("LONG_COMMON_NAME like", value, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameNotLike(String value) {
			addCriterion("LONG_COMMON_NAME not like", value, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameIn(List<String> values) {
			addCriterion("LONG_COMMON_NAME in", values, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameNotIn(List<String> values) {
			addCriterion("LONG_COMMON_NAME not in", values, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameBetween(String value1, String value2) {
			addCriterion("LONG_COMMON_NAME between", value1, value2, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andLongCommonNameNotBetween(String value1, String value2) {
			addCriterion("LONG_COMMON_NAME not between", value1, value2, "longCommonName");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsIsNull() {
			addCriterion("EXAMPLE_UCUM_UNITS is null");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsIsNotNull() {
			addCriterion("EXAMPLE_UCUM_UNITS is not null");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsEqualTo(String value) {
			addCriterion("EXAMPLE_UCUM_UNITS =", value, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsNotEqualTo(String value) {
			addCriterion("EXAMPLE_UCUM_UNITS <>", value, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsGreaterThan(String value) {
			addCriterion("EXAMPLE_UCUM_UNITS >", value, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsGreaterThanOrEqualTo(String value) {
			addCriterion("EXAMPLE_UCUM_UNITS >=", value, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsLessThan(String value) {
			addCriterion("EXAMPLE_UCUM_UNITS <", value, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsLessThanOrEqualTo(String value) {
			addCriterion("EXAMPLE_UCUM_UNITS <=", value, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsLike(String value) {
			addCriterion("EXAMPLE_UCUM_UNITS like", value, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsNotLike(String value) {
			addCriterion("EXAMPLE_UCUM_UNITS not like", value, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsIn(List<String> values) {
			addCriterion("EXAMPLE_UCUM_UNITS in", values, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsNotIn(List<String> values) {
			addCriterion("EXAMPLE_UCUM_UNITS not in", values, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsBetween(String value1, String value2) {
			addCriterion("EXAMPLE_UCUM_UNITS between", value1, value2, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andExampleUcumUnitsNotBetween(String value1, String value2) {
			addCriterion("EXAMPLE_UCUM_UNITS not between", value1, value2, "exampleUcumUnits");
			return (Criteria) this;
		}

		public Criteria andStatusReasonIsNull() {
			addCriterion("STATUS_REASON is null");
			return (Criteria) this;
		}

		public Criteria andStatusReasonIsNotNull() {
			addCriterion("STATUS_REASON is not null");
			return (Criteria) this;
		}

		public Criteria andStatusReasonEqualTo(String value) {
			addCriterion("STATUS_REASON =", value, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonNotEqualTo(String value) {
			addCriterion("STATUS_REASON <>", value, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonGreaterThan(String value) {
			addCriterion("STATUS_REASON >", value, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS_REASON >=", value, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonLessThan(String value) {
			addCriterion("STATUS_REASON <", value, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonLessThanOrEqualTo(String value) {
			addCriterion("STATUS_REASON <=", value, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonLike(String value) {
			addCriterion("STATUS_REASON like", value, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonNotLike(String value) {
			addCriterion("STATUS_REASON not like", value, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonIn(List<String> values) {
			addCriterion("STATUS_REASON in", values, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonNotIn(List<String> values) {
			addCriterion("STATUS_REASON not in", values, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonBetween(String value1, String value2) {
			addCriterion("STATUS_REASON between", value1, value2, "statusReason");
			return (Criteria) this;
		}

		public Criteria andStatusReasonNotBetween(String value1, String value2) {
			addCriterion("STATUS_REASON not between", value1, value2, "statusReason");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankIsNull() {
			addCriterion("COMMON_TEST_RANK is null");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankIsNotNull() {
			addCriterion("COMMON_TEST_RANK is not null");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankEqualTo(Integer value) {
			addCriterion("COMMON_TEST_RANK =", value, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankNotEqualTo(Integer value) {
			addCriterion("COMMON_TEST_RANK <>", value, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankGreaterThan(Integer value) {
			addCriterion("COMMON_TEST_RANK >", value, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankGreaterThanOrEqualTo(Integer value) {
			addCriterion("COMMON_TEST_RANK >=", value, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankLessThan(Integer value) {
			addCriterion("COMMON_TEST_RANK <", value, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankLessThanOrEqualTo(Integer value) {
			addCriterion("COMMON_TEST_RANK <=", value, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankIn(List<Integer> values) {
			addCriterion("COMMON_TEST_RANK in", values, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankNotIn(List<Integer> values) {
			addCriterion("COMMON_TEST_RANK not in", values, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankBetween(Integer value1, Integer value2) {
			addCriterion("COMMON_TEST_RANK between", value1, value2, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonTestRankNotBetween(Integer value1, Integer value2) {
			addCriterion("COMMON_TEST_RANK not between", value1, value2, "commonTestRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankIsNull() {
			addCriterion("COMMON_ORDER_RANK is null");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankIsNotNull() {
			addCriterion("COMMON_ORDER_RANK is not null");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankEqualTo(Integer value) {
			addCriterion("COMMON_ORDER_RANK =", value, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankNotEqualTo(Integer value) {
			addCriterion("COMMON_ORDER_RANK <>", value, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankGreaterThan(Integer value) {
			addCriterion("COMMON_ORDER_RANK >", value, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankGreaterThanOrEqualTo(Integer value) {
			addCriterion("COMMON_ORDER_RANK >=", value, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankLessThan(Integer value) {
			addCriterion("COMMON_ORDER_RANK <", value, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankLessThanOrEqualTo(Integer value) {
			addCriterion("COMMON_ORDER_RANK <=", value, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankIn(List<Integer> values) {
			addCriterion("COMMON_ORDER_RANK in", values, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankNotIn(List<Integer> values) {
			addCriterion("COMMON_ORDER_RANK not in", values, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankBetween(Integer value1, Integer value2) {
			addCriterion("COMMON_ORDER_RANK between", value1, value2, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andCommonOrderRankNotBetween(Integer value1, Integer value2) {
			addCriterion("COMMON_ORDER_RANK not between", value1, value2, "commonOrderRank");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureIsNull() {
			addCriterion("HL7_ATTACHMENT_STRUCTURE is null");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureIsNotNull() {
			addCriterion("HL7_ATTACHMENT_STRUCTURE is not null");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureEqualTo(String value) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE =", value, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureNotEqualTo(String value) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE <>", value, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureGreaterThan(String value) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE >", value, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureGreaterThanOrEqualTo(String value) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE >=", value, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureLessThan(String value) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE <", value, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureLessThanOrEqualTo(String value) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE <=", value, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureLike(String value) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE like", value, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureNotLike(String value) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE not like", value, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureIn(List<String> values) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE in", values, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureNotIn(List<String> values) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE not in", values, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureBetween(String value1, String value2) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE between", value1, value2, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andHl7AttachmentStructureNotBetween(String value1, String value2) {
			addCriterion("HL7_ATTACHMENT_STRUCTURE not between", value1, value2, "hl7AttachmentStructure");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkIsNull() {
			addCriterion("EXTERNAL_COPYRIGHT_LINK is null");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkIsNotNull() {
			addCriterion("EXTERNAL_COPYRIGHT_LINK is not null");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkEqualTo(String value) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK =", value, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkNotEqualTo(String value) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK <>", value, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkGreaterThan(String value) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK >", value, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkGreaterThanOrEqualTo(String value) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK >=", value, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkLessThan(String value) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK <", value, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkLessThanOrEqualTo(String value) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK <=", value, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkLike(String value) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK like", value, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkNotLike(String value) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK not like", value, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkIn(List<String> values) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK in", values, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkNotIn(List<String> values) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK not in", values, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkBetween(String value1, String value2) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK between", value1, value2, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andExternalCopyrightLinkNotBetween(String value1, String value2) {
			addCriterion("EXTERNAL_COPYRIGHT_LINK not between", value1, value2, "externalCopyrightLink");
			return (Criteria) this;
		}

		public Criteria andPaneltypeIsNull() {
			addCriterion("PanelType is null");
			return (Criteria) this;
		}

		public Criteria andPaneltypeIsNotNull() {
			addCriterion("PanelType is not null");
			return (Criteria) this;
		}

		public Criteria andPaneltypeEqualTo(String value) {
			addCriterion("PanelType =", value, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeNotEqualTo(String value) {
			addCriterion("PanelType <>", value, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeGreaterThan(String value) {
			addCriterion("PanelType >", value, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeGreaterThanOrEqualTo(String value) {
			addCriterion("PanelType >=", value, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeLessThan(String value) {
			addCriterion("PanelType <", value, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeLessThanOrEqualTo(String value) {
			addCriterion("PanelType <=", value, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeLike(String value) {
			addCriterion("PanelType like", value, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeNotLike(String value) {
			addCriterion("PanelType not like", value, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeIn(List<String> values) {
			addCriterion("PanelType in", values, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeNotIn(List<String> values) {
			addCriterion("PanelType not in", values, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeBetween(String value1, String value2) {
			addCriterion("PanelType between", value1, value2, "paneltype");
			return (Criteria) this;
		}

		public Criteria andPaneltypeNotBetween(String value1, String value2) {
			addCriterion("PanelType not between", value1, value2, "paneltype");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryIsNull() {
			addCriterion("AskAtOrderEntry is null");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryIsNotNull() {
			addCriterion("AskAtOrderEntry is not null");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryEqualTo(String value) {
			addCriterion("AskAtOrderEntry =", value, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryNotEqualTo(String value) {
			addCriterion("AskAtOrderEntry <>", value, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryGreaterThan(String value) {
			addCriterion("AskAtOrderEntry >", value, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryGreaterThanOrEqualTo(String value) {
			addCriterion("AskAtOrderEntry >=", value, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryLessThan(String value) {
			addCriterion("AskAtOrderEntry <", value, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryLessThanOrEqualTo(String value) {
			addCriterion("AskAtOrderEntry <=", value, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryLike(String value) {
			addCriterion("AskAtOrderEntry like", value, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryNotLike(String value) {
			addCriterion("AskAtOrderEntry not like", value, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryIn(List<String> values) {
			addCriterion("AskAtOrderEntry in", values, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryNotIn(List<String> values) {
			addCriterion("AskAtOrderEntry not in", values, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryBetween(String value1, String value2) {
			addCriterion("AskAtOrderEntry between", value1, value2, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAskatorderentryNotBetween(String value1, String value2) {
			addCriterion("AskAtOrderEntry not between", value1, value2, "askatorderentry");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsIsNull() {
			addCriterion("AssociatedObservations is null");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsIsNotNull() {
			addCriterion("AssociatedObservations is not null");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsEqualTo(String value) {
			addCriterion("AssociatedObservations =", value, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsNotEqualTo(String value) {
			addCriterion("AssociatedObservations <>", value, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsGreaterThan(String value) {
			addCriterion("AssociatedObservations >", value, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsGreaterThanOrEqualTo(String value) {
			addCriterion("AssociatedObservations >=", value, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsLessThan(String value) {
			addCriterion("AssociatedObservations <", value, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsLessThanOrEqualTo(String value) {
			addCriterion("AssociatedObservations <=", value, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsLike(String value) {
			addCriterion("AssociatedObservations like", value, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsNotLike(String value) {
			addCriterion("AssociatedObservations not like", value, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsIn(List<String> values) {
			addCriterion("AssociatedObservations in", values, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsNotIn(List<String> values) {
			addCriterion("AssociatedObservations not in", values, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsBetween(String value1, String value2) {
			addCriterion("AssociatedObservations between", value1, value2, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andAssociatedobservationsNotBetween(String value1, String value2) {
			addCriterion("AssociatedObservations not between", value1, value2, "associatedobservations");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedIsNull() {
			addCriterion("VersionFirstReleased is null");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedIsNotNull() {
			addCriterion("VersionFirstReleased is not null");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedEqualTo(String value) {
			addCriterion("VersionFirstReleased =", value, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedNotEqualTo(String value) {
			addCriterion("VersionFirstReleased <>", value, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedGreaterThan(String value) {
			addCriterion("VersionFirstReleased >", value, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedGreaterThanOrEqualTo(String value) {
			addCriterion("VersionFirstReleased >=", value, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedLessThan(String value) {
			addCriterion("VersionFirstReleased <", value, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedLessThanOrEqualTo(String value) {
			addCriterion("VersionFirstReleased <=", value, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedLike(String value) {
			addCriterion("VersionFirstReleased like", value, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedNotLike(String value) {
			addCriterion("VersionFirstReleased not like", value, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedIn(List<String> values) {
			addCriterion("VersionFirstReleased in", values, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedNotIn(List<String> values) {
			addCriterion("VersionFirstReleased not in", values, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedBetween(String value1, String value2) {
			addCriterion("VersionFirstReleased between", value1, value2, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andVersionfirstreleasedNotBetween(String value1, String value2) {
			addCriterion("VersionFirstReleased not between", value1, value2, "versionfirstreleased");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestIsNull() {
			addCriterion("ValidHL7AttachmentRequest is null");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestIsNotNull() {
			addCriterion("ValidHL7AttachmentRequest is not null");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestEqualTo(String value) {
			addCriterion("ValidHL7AttachmentRequest =", value, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestNotEqualTo(String value) {
			addCriterion("ValidHL7AttachmentRequest <>", value, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestGreaterThan(String value) {
			addCriterion("ValidHL7AttachmentRequest >", value, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestGreaterThanOrEqualTo(String value) {
			addCriterion("ValidHL7AttachmentRequest >=", value, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestLessThan(String value) {
			addCriterion("ValidHL7AttachmentRequest <", value, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestLessThanOrEqualTo(String value) {
			addCriterion("ValidHL7AttachmentRequest <=", value, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestLike(String value) {
			addCriterion("ValidHL7AttachmentRequest like", value, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestNotLike(String value) {
			addCriterion("ValidHL7AttachmentRequest not like", value, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestIn(List<String> values) {
			addCriterion("ValidHL7AttachmentRequest in", values, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestNotIn(List<String> values) {
			addCriterion("ValidHL7AttachmentRequest not in", values, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestBetween(String value1, String value2) {
			addCriterion("ValidHL7AttachmentRequest between", value1, value2, "validhl7attachmentrequest");
			return (Criteria) this;
		}

		public Criteria andValidhl7attachmentrequestNotBetween(String value1, String value2) {
			addCriterion("ValidHL7AttachmentRequest not between", value1, value2, "validhl7attachmentrequest");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loinc
     *
     * @mbg.generated do_not_delete_during_merge Thu May 23 19:01:25 EDT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}