package com.empirestateids.domain;

public class LoincWithBLOBs extends Loinc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loinc.EXTERNAL_COPYRIGHT_NOTICE
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	private String externalCopyrightNotice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loinc.STATUS_TEXT
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	private String statusText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loinc.CHANGE_REASON_PUBLIC
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	private String changeReasonPublic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loinc.DisplayName
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	private String displayname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loinc.EXTERNAL_COPYRIGHT_NOTICE
	 * @return  the value of loinc.EXTERNAL_COPYRIGHT_NOTICE
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public String getExternalCopyrightNotice() {
		return externalCopyrightNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loinc.EXTERNAL_COPYRIGHT_NOTICE
	 * @param externalCopyrightNotice  the value for loinc.EXTERNAL_COPYRIGHT_NOTICE
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public void setExternalCopyrightNotice(String externalCopyrightNotice) {
		this.externalCopyrightNotice = externalCopyrightNotice == null ? null : externalCopyrightNotice.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loinc.STATUS_TEXT
	 * @return  the value of loinc.STATUS_TEXT
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public String getStatusText() {
		return statusText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loinc.STATUS_TEXT
	 * @param statusText  the value for loinc.STATUS_TEXT
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public void setStatusText(String statusText) {
		this.statusText = statusText == null ? null : statusText.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loinc.CHANGE_REASON_PUBLIC
	 * @return  the value of loinc.CHANGE_REASON_PUBLIC
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public String getChangeReasonPublic() {
		return changeReasonPublic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loinc.CHANGE_REASON_PUBLIC
	 * @param changeReasonPublic  the value for loinc.CHANGE_REASON_PUBLIC
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public void setChangeReasonPublic(String changeReasonPublic) {
		this.changeReasonPublic = changeReasonPublic == null ? null : changeReasonPublic.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loinc.DisplayName
	 * @return  the value of loinc.DisplayName
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public String getDisplayname() {
		return displayname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loinc.DisplayName
	 * @param displayname  the value for loinc.DisplayName
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	public void setDisplayname(String displayname) {
		this.displayname = displayname == null ? null : displayname.trim();
	}
}