package com.empirestateids.domain;

import java.io.Serializable;
import java.util.Date;

public class Lookup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lookup.lookup_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer lookupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lookup.lookup_name
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private String lookupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lookup.code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lookup.value
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lookup.sort_order
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lookup.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lookup.created
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lookup.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Integer updatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lookup.updated
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lookup.lookup_id
     *
     * @return the value of lookup.lookup_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getLookupId() {
        return lookupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lookup.lookup_id
     *
     * @param lookupId the value for lookup.lookup_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setLookupId(Integer lookupId) {
        this.lookupId = lookupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lookup.lookup_name
     *
     * @return the value of lookup.lookup_name
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public String getLookupName() {
        return lookupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lookup.lookup_name
     *
     * @param lookupName the value for lookup.lookup_name
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setLookupName(String lookupName) {
        this.lookupName = lookupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lookup.code
     *
     * @return the value of lookup.code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lookup.code
     *
     * @param code the value for lookup.code
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lookup.value
     *
     * @return the value of lookup.value
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lookup.value
     *
     * @param value the value for lookup.value
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lookup.sort_order
     *
     * @return the value of lookup.sort_order
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lookup.sort_order
     *
     * @param sortOrder the value for lookup.sort_order
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lookup.created_by_id
     *
     * @return the value of lookup.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lookup.created_by_id
     *
     * @param createdById the value for lookup.created_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lookup.created
     *
     * @return the value of lookup.created
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lookup.created
     *
     * @param created the value for lookup.created
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lookup.updated_by_id
     *
     * @return the value of lookup.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Integer getUpdatedById() {
        return updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lookup.updated_by_id
     *
     * @param updatedById the value for lookup.updated_by_id
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setUpdatedById(Integer updatedById) {
        this.updatedById = updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lookup.updated
     *
     * @return the value of lookup.updated
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lookup.updated
     *
     * @param updated the value for lookup.updated
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Lookup other = (Lookup) that;
        return (this.getLookupId() == null ? other.getLookupId() == null : this.getLookupId().equals(other.getLookupId()))
            && (this.getLookupName() == null ? other.getLookupName() == null : this.getLookupName().equals(other.getLookupName()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getSortOrder() == null ? other.getSortOrder() == null : this.getSortOrder().equals(other.getSortOrder()))
            && (this.getCreatedById() == null ? other.getCreatedById() == null : this.getCreatedById().equals(other.getCreatedById()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getUpdatedById() == null ? other.getUpdatedById() == null : this.getUpdatedById().equals(other.getUpdatedById()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLookupId() == null) ? 0 : getLookupId().hashCode());
        result = prime * result + ((getLookupName() == null) ? 0 : getLookupName().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getSortOrder() == null) ? 0 : getSortOrder().hashCode());
        result = prime * result + ((getCreatedById() == null) ? 0 : getCreatedById().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getUpdatedById() == null) ? 0 : getUpdatedById().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lookupId=").append(lookupId);
        sb.append(", lookupName=").append(lookupName);
        sb.append(", code=").append(code);
        sb.append(", value=").append(value);
        sb.append(", sortOrder=").append(sortOrder);
        sb.append(", createdById=").append(createdById);
        sb.append(", created=").append(created);
        sb.append(", updatedById=").append(updatedById);
        sb.append(", updated=").append(updated);
        sb.append("]");
        return sb.toString();
    }
}