package com.empirestateids.domain;

import java.io.Serializable;
import java.util.Date;

public class Phone implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.phone_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private Integer phoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.contact_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private Integer contactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.phone_number
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.phone_ext
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private Integer phoneExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.phone_type_code
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private Integer phoneTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.isd_code
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private Integer isdCode = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.created_by_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private Integer createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.created
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.updated_by_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private Integer updatedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.updated
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.phone_id
     *
     * @return the value of phone.phone_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.phone_id
     *
     * @param phoneId the value for phone.phone_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.contact_id
     *
     * @return the value of phone.contact_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public Integer getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.contact_id
     *
     * @param contactId the value for phone.contact_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.phone_number
     *
     * @return the value of phone.phone_number
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.phone_number
     *
     * @param phoneNumber the value for phone.phone_number
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.phone_ext
     *
     * @return the value of phone.phone_ext
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public Integer getPhoneExt() {
        return phoneExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.phone_ext
     *
     * @param phoneExt the value for phone.phone_ext
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setPhoneExt(Integer phoneExt) {
        this.phoneExt = phoneExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.phone_type_code
     *
     * @return the value of phone.phone_type_code
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public Integer getPhoneTypeCode() {
        return phoneTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.phone_type_code
     *
     * @param phoneTypeCode the value for phone.phone_type_code
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setPhoneTypeCode(Integer phoneTypeCode) {
        this.phoneTypeCode = phoneTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.isd_code
     *
     * @return the value of phone.isd_code
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public Integer getIsdCode() {
        return isdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.isd_code
     *
     * @param isdCode the value for phone.isd_code
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setIsdCode(Integer isdCode) {
        this.isdCode = isdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.created_by_id
     *
     * @return the value of phone.created_by_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public Integer getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.created_by_id
     *
     * @param createdById the value for phone.created_by_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.created
     *
     * @return the value of phone.created
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.created
     *
     * @param created the value for phone.created
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.updated_by_id
     *
     * @return the value of phone.updated_by_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public Integer getUpdatedById() {
        return updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.updated_by_id
     *
     * @param updatedById the value for phone.updated_by_id
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setUpdatedById(Integer updatedById) {
        this.updatedById = updatedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.updated
     *
     * @return the value of phone.updated
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.updated
     *
     * @param updated the value for phone.updated
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Phone other = (Phone) that;
        return (this.getPhoneId() == null ? other.getPhoneId() == null : this.getPhoneId().equals(other.getPhoneId()))
            && (this.getContactId() == null ? other.getContactId() == null : this.getContactId().equals(other.getContactId()))
            && (this.getPhoneNumber() == null ? other.getPhoneNumber() == null : this.getPhoneNumber().equals(other.getPhoneNumber()))
            && (this.getPhoneExt() == null ? other.getPhoneExt() == null : this.getPhoneExt().equals(other.getPhoneExt()))
            && (this.getPhoneTypeCode() == null ? other.getPhoneTypeCode() == null : this.getPhoneTypeCode().equals(other.getPhoneTypeCode()))
            && (this.getIsdCode() == null ? other.getIsdCode() == null : this.getIsdCode().equals(other.getIsdCode()))
            && (this.getCreatedById() == null ? other.getCreatedById() == null : this.getCreatedById().equals(other.getCreatedById()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getUpdatedById() == null ? other.getUpdatedById() == null : this.getUpdatedById().equals(other.getUpdatedById()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPhoneId() == null) ? 0 : getPhoneId().hashCode());
        result = prime * result + ((getContactId() == null) ? 0 : getContactId().hashCode());
        result = prime * result + ((getPhoneNumber() == null) ? 0 : getPhoneNumber().hashCode());
        result = prime * result + ((getPhoneExt() == null) ? 0 : getPhoneExt().hashCode());
        result = prime * result + ((getPhoneTypeCode() == null) ? 0 : getPhoneTypeCode().hashCode());
        result = prime * result + ((getIsdCode() == null) ? 0 : getIsdCode().hashCode());
        result = prime * result + ((getCreatedById() == null) ? 0 : getCreatedById().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getUpdatedById() == null) ? 0 : getUpdatedById().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", phoneId=").append(phoneId);
        sb.append(", contactId=").append(contactId);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", phoneExt=").append(phoneExt);
        sb.append(", phoneTypeCode=").append(phoneTypeCode);
        sb.append(", isdCode=").append(isdCode);
        sb.append(", createdById=").append(createdById);
        sb.append(", created=").append(created);
        sb.append(", updatedById=").append(updatedById);
        sb.append(", updated=").append(updated);
        sb.append("]");
        return sb.toString();
    }
}