package com.empirestateids.domain;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class RxNormCodesExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public RxNormCodesExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRxCodePkIsNull() {
			addCriterion("RX_CODE_PK is null");
			return (Criteria) this;
		}

		public Criteria andRxCodePkIsNotNull() {
			addCriterion("RX_CODE_PK is not null");
			return (Criteria) this;
		}

		public Criteria andRxCodePkEqualTo(Long value) {
			addCriterion("RX_CODE_PK =", value, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andRxCodePkNotEqualTo(Long value) {
			addCriterion("RX_CODE_PK <>", value, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andRxCodePkGreaterThan(Long value) {
			addCriterion("RX_CODE_PK >", value, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andRxCodePkGreaterThanOrEqualTo(Long value) {
			addCriterion("RX_CODE_PK >=", value, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andRxCodePkLessThan(Long value) {
			addCriterion("RX_CODE_PK <", value, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andRxCodePkLessThanOrEqualTo(Long value) {
			addCriterion("RX_CODE_PK <=", value, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andRxCodePkIn(List<Long> values) {
			addCriterion("RX_CODE_PK in", values, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andRxCodePkNotIn(List<Long> values) {
			addCriterion("RX_CODE_PK not in", values, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andRxCodePkBetween(Long value1, Long value2) {
			addCriterion("RX_CODE_PK between", value1, value2, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andRxCodePkNotBetween(Long value1, Long value2) {
			addCriterion("RX_CODE_PK not between", value1, value2, "rxCodePk");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeIsNull() {
			addCriterion("NDC11_CODE is null");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeIsNotNull() {
			addCriterion("NDC11_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeEqualTo(Long value) {
			addCriterion("NDC11_CODE =", value, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeNotEqualTo(Long value) {
			addCriterion("NDC11_CODE <>", value, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeGreaterThan(Long value) {
			addCriterion("NDC11_CODE >", value, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeGreaterThanOrEqualTo(Long value) {
			addCriterion("NDC11_CODE >=", value, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeLessThan(Long value) {
			addCriterion("NDC11_CODE <", value, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeLessThanOrEqualTo(Long value) {
			addCriterion("NDC11_CODE <=", value, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeIn(List<Long> values) {
			addCriterion("NDC11_CODE in", values, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeNotIn(List<Long> values) {
			addCriterion("NDC11_CODE not in", values, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeBetween(Long value1, Long value2) {
			addCriterion("NDC11_CODE between", value1, value2, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeNotBetween(Long value1, Long value2) {
			addCriterion("NDC11_CODE not between", value1, value2, "ndc11Code");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringIsNull() {
			addCriterion("NDC11_CODE_STRING is null");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringIsNotNull() {
			addCriterion("NDC11_CODE_STRING is not null");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringEqualTo(String value) {
			addCriterion("NDC11_CODE_STRING =", value, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringNotEqualTo(String value) {
			addCriterion("NDC11_CODE_STRING <>", value, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringGreaterThan(String value) {
			addCriterion("NDC11_CODE_STRING >", value, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringGreaterThanOrEqualTo(String value) {
			addCriterion("NDC11_CODE_STRING >=", value, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringLessThan(String value) {
			addCriterion("NDC11_CODE_STRING <", value, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringLessThanOrEqualTo(String value) {
			addCriterion("NDC11_CODE_STRING <=", value, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringLike(String value) {
			addCriterion("NDC11_CODE_STRING like", value, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringNotLike(String value) {
			addCriterion("NDC11_CODE_STRING not like", value, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringIn(List<String> values) {
			addCriterion("NDC11_CODE_STRING in", values, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringNotIn(List<String> values) {
			addCriterion("NDC11_CODE_STRING not in", values, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringBetween(String value1, String value2) {
			addCriterion("NDC11_CODE_STRING between", value1, value2, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andNdc11CodeStringNotBetween(String value1, String value2) {
			addCriterion("NDC11_CODE_STRING not between", value1, value2, "ndc11CodeString");
			return (Criteria) this;
		}

		public Criteria andConceptNameIsNull() {
			addCriterion("CONCEPT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andConceptNameIsNotNull() {
			addCriterion("CONCEPT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andConceptNameEqualTo(String value) {
			addCriterion("CONCEPT_NAME =", value, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameNotEqualTo(String value) {
			addCriterion("CONCEPT_NAME <>", value, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameGreaterThan(String value) {
			addCriterion("CONCEPT_NAME >", value, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameGreaterThanOrEqualTo(String value) {
			addCriterion("CONCEPT_NAME >=", value, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameLessThan(String value) {
			addCriterion("CONCEPT_NAME <", value, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameLessThanOrEqualTo(String value) {
			addCriterion("CONCEPT_NAME <=", value, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameLike(String value) {
			addCriterion("CONCEPT_NAME like", value, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameNotLike(String value) {
			addCriterion("CONCEPT_NAME not like", value, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameIn(List<String> values) {
			addCriterion("CONCEPT_NAME in", values, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameNotIn(List<String> values) {
			addCriterion("CONCEPT_NAME not in", values, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameBetween(String value1, String value2) {
			addCriterion("CONCEPT_NAME between", value1, value2, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptNameNotBetween(String value1, String value2) {
			addCriterion("CONCEPT_NAME not between", value1, value2, "conceptName");
			return (Criteria) this;
		}

		public Criteria andConceptStatusIsNull() {
			addCriterion("CONCEPT_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andConceptStatusIsNotNull() {
			addCriterion("CONCEPT_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andConceptStatusEqualTo(String value) {
			addCriterion("CONCEPT_STATUS =", value, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusNotEqualTo(String value) {
			addCriterion("CONCEPT_STATUS <>", value, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusGreaterThan(String value) {
			addCriterion("CONCEPT_STATUS >", value, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusGreaterThanOrEqualTo(String value) {
			addCriterion("CONCEPT_STATUS >=", value, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusLessThan(String value) {
			addCriterion("CONCEPT_STATUS <", value, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusLessThanOrEqualTo(String value) {
			addCriterion("CONCEPT_STATUS <=", value, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusLike(String value) {
			addCriterion("CONCEPT_STATUS like", value, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusNotLike(String value) {
			addCriterion("CONCEPT_STATUS not like", value, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusIn(List<String> values) {
			addCriterion("CONCEPT_STATUS in", values, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusNotIn(List<String> values) {
			addCriterion("CONCEPT_STATUS not in", values, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusBetween(String value1, String value2) {
			addCriterion("CONCEPT_STATUS between", value1, value2, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andConceptStatusNotBetween(String value1, String value2) {
			addCriterion("CONCEPT_STATUS not between", value1, value2, "conceptStatus");
			return (Criteria) this;
		}

		public Criteria andRxcuiIsNull() {
			addCriterion("RXCUI is null");
			return (Criteria) this;
		}

		public Criteria andRxcuiIsNotNull() {
			addCriterion("RXCUI is not null");
			return (Criteria) this;
		}

		public Criteria andRxcuiEqualTo(String value) {
			addCriterion("RXCUI =", value, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiNotEqualTo(String value) {
			addCriterion("RXCUI <>", value, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiGreaterThan(String value) {
			addCriterion("RXCUI >", value, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiGreaterThanOrEqualTo(String value) {
			addCriterion("RXCUI >=", value, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiLessThan(String value) {
			addCriterion("RXCUI <", value, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiLessThanOrEqualTo(String value) {
			addCriterion("RXCUI <=", value, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiLike(String value) {
			addCriterion("RXCUI like", value, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiNotLike(String value) {
			addCriterion("RXCUI not like", value, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiIn(List<String> values) {
			addCriterion("RXCUI in", values, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiNotIn(List<String> values) {
			addCriterion("RXCUI not in", values, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiBetween(String value1, String value2) {
			addCriterion("RXCUI between", value1, value2, "rxcui");
			return (Criteria) this;
		}

		public Criteria andRxcuiNotBetween(String value1, String value2) {
			addCriterion("RXCUI not between", value1, value2, "rxcui");
			return (Criteria) this;
		}

		public Criteria andTtyIsNull() {
			addCriterion("TTY is null");
			return (Criteria) this;
		}

		public Criteria andTtyIsNotNull() {
			addCriterion("TTY is not null");
			return (Criteria) this;
		}

		public Criteria andTtyEqualTo(String value) {
			addCriterion("TTY =", value, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyNotEqualTo(String value) {
			addCriterion("TTY <>", value, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyGreaterThan(String value) {
			addCriterion("TTY >", value, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyGreaterThanOrEqualTo(String value) {
			addCriterion("TTY >=", value, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyLessThan(String value) {
			addCriterion("TTY <", value, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyLessThanOrEqualTo(String value) {
			addCriterion("TTY <=", value, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyLike(String value) {
			addCriterion("TTY like", value, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyNotLike(String value) {
			addCriterion("TTY not like", value, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyIn(List<String> values) {
			addCriterion("TTY in", values, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyNotIn(List<String> values) {
			addCriterion("TTY not in", values, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyBetween(String value1, String value2) {
			addCriterion("TTY between", value1, value2, "tty");
			return (Criteria) this;
		}

		public Criteria andTtyNotBetween(String value1, String value2) {
			addCriterion("TTY not between", value1, value2, "tty");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreatedDateIsNull() {
			addCriterion("CREATED_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreatedDateIsNotNull() {
			addCriterion("CREATED_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedDateEqualTo(Date value) {
			addCriterion("CREATED_DATE =", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateNotEqualTo(Date value) {
			addCriterion("CREATED_DATE <>", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateGreaterThan(Date value) {
			addCriterion("CREATED_DATE >", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATED_DATE >=", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateLessThan(Date value) {
			addCriterion("CREATED_DATE <", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
			addCriterion("CREATED_DATE <=", value, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateIn(List<Date> values) {
			addCriterion("CREATED_DATE in", values, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateNotIn(List<Date> values) {
			addCriterion("CREATED_DATE not in", values, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateBetween(Date value1, Date value2) {
			addCriterion("CREATED_DATE between", value1, value2, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
			addCriterion("CREATED_DATE not between", value1, value2, "createdDate");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdIsNull() {
			addCriterion("CREATED_BY_ID is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdIsNotNull() {
			addCriterion("CREATED_BY_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdEqualTo(String value) {
			addCriterion("CREATED_BY_ID =", value, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdNotEqualTo(String value) {
			addCriterion("CREATED_BY_ID <>", value, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdGreaterThan(String value) {
			addCriterion("CREATED_BY_ID >", value, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATED_BY_ID >=", value, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdLessThan(String value) {
			addCriterion("CREATED_BY_ID <", value, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdLessThanOrEqualTo(String value) {
			addCriterion("CREATED_BY_ID <=", value, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdLike(String value) {
			addCriterion("CREATED_BY_ID like", value, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdNotLike(String value) {
			addCriterion("CREATED_BY_ID not like", value, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdIn(List<String> values) {
			addCriterion("CREATED_BY_ID in", values, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdNotIn(List<String> values) {
			addCriterion("CREATED_BY_ID not in", values, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdBetween(String value1, String value2) {
			addCriterion("CREATED_BY_ID between", value1, value2, "createdById");
			return (Criteria) this;
		}

		public Criteria andCreatedByIdNotBetween(String value1, String value2) {
			addCriterion("CREATED_BY_ID not between", value1, value2, "createdById");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateIsNull() {
			addCriterion("UPDATED_DATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateIsNotNull() {
			addCriterion("UPDATED_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateEqualTo(Date value) {
			addCriterion("UPDATED_DATE =", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateNotEqualTo(Date value) {
			addCriterion("UPDATED_DATE <>", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateGreaterThan(Date value) {
			addCriterion("UPDATED_DATE >", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATED_DATE >=", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateLessThan(Date value) {
			addCriterion("UPDATED_DATE <", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATED_DATE <=", value, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateIn(List<Date> values) {
			addCriterion("UPDATED_DATE in", values, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateNotIn(List<Date> values) {
			addCriterion("UPDATED_DATE not in", values, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateBetween(Date value1, Date value2) {
			addCriterion("UPDATED_DATE between", value1, value2, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATED_DATE not between", value1, value2, "updatedDate");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdIsNull() {
			addCriterion("UPDATED_BY_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdIsNotNull() {
			addCriterion("UPDATED_BY_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdEqualTo(String value) {
			addCriterion("UPDATED_BY_ID =", value, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdNotEqualTo(String value) {
			addCriterion("UPDATED_BY_ID <>", value, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdGreaterThan(String value) {
			addCriterion("UPDATED_BY_ID >", value, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATED_BY_ID >=", value, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdLessThan(String value) {
			addCriterion("UPDATED_BY_ID <", value, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATED_BY_ID <=", value, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdLike(String value) {
			addCriterion("UPDATED_BY_ID like", value, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdNotLike(String value) {
			addCriterion("UPDATED_BY_ID not like", value, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdIn(List<String> values) {
			addCriterion("UPDATED_BY_ID in", values, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdNotIn(List<String> values) {
			addCriterion("UPDATED_BY_ID not in", values, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdBetween(String value1, String value2) {
			addCriterion("UPDATED_BY_ID between", value1, value2, "updatedById");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIdNotBetween(String value1, String value2) {
			addCriterion("UPDATED_BY_ID not between", value1, value2, "updatedById");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rxnorm_codes
	 * @mbg.generated  Wed Jun 19 13:38:47 EDT 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rxnorm_codes
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 03 21:34:38 EDT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}