package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.AclClass;
import com.empirestateids.domain.AclClassCriteria;

public interface AclClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int countByExample(AclClassCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByExample(AclClassCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insert(AclClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insertSelective(AclClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<AclClass> selectByExampleWithRowbounds(AclClassCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<AclClass> selectByExample(AclClassCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    AclClass selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExampleSelective(@Param("record") AclClass record, @Param("example") AclClassCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExample(@Param("record") AclClass record, @Param("example") AclClassCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKeySelective(AclClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_class
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKey(AclClass record);
}