package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.AclEntry;
import com.empirestateids.domain.AclEntryCriteria;

public interface AclEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int countByExample(AclEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByExample(AclEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insert(AclEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insertSelective(AclEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<AclEntry> selectByExampleWithRowbounds(AclEntryCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<AclEntry> selectByExample(AclEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    AclEntry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExampleSelective(@Param("record") AclEntry record, @Param("example") AclEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExample(@Param("record") AclEntry record, @Param("example") AclEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKeySelective(AclEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_entry
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKey(AclEntry record);
}