package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.AclObjectIdentity;
import com.empirestateids.domain.AclObjectIdentityCriteria;

public interface AclObjectIdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int countByExample(AclObjectIdentityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByExample(AclObjectIdentityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insert(AclObjectIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insertSelective(AclObjectIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<AclObjectIdentity> selectByExampleWithRowbounds(AclObjectIdentityCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<AclObjectIdentity> selectByExample(AclObjectIdentityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    AclObjectIdentity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExampleSelective(@Param("record") AclObjectIdentity record, @Param("example") AclObjectIdentityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExample(@Param("record") AclObjectIdentity record, @Param("example") AclObjectIdentityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKeySelective(AclObjectIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_object_identity
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKey(AclObjectIdentity record);
}