package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.AclSid;
import com.empirestateids.domain.AclSidCriteria;

public interface AclSidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int countByExample(AclSidCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByExample(AclSidCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insert(AclSid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insertSelective(AclSid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<AclSid> selectByExampleWithRowbounds(AclSidCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<AclSid> selectByExample(AclSidCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    AclSid selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExampleSelective(@Param("record") AclSid record, @Param("example") AclSidCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExample(@Param("record") AclSid record, @Param("example") AclSidCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKeySelective(AclSid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_sid
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKey(AclSid record);
}