package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.Address;
import com.empirestateids.domain.AddressCriteria;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int countByExample(AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByExample(AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<Address> selectByExampleWithRowbounds(AddressCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<Address> selectByExample(AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    Address selectByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExampleSelective(@Param("record") Address record, @Param("example") AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExample(@Param("record") Address record, @Param("example") AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKey(Address record);
}