package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.Contact;
import com.empirestateids.domain.ContactCriteria;

public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int countByExample(ContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByExample(ContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByPrimaryKey(Integer contactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insertSelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<Contact> selectByExampleWithRowbounds(ContactCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<Contact> selectByExample(ContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    Contact selectByPrimaryKey(Integer contactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExampleSelective(@Param("record") Contact record, @Param("example") ContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExample(@Param("record") Contact record, @Param("example") ContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKeySelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKey(Contact record);
    
    /**
     * This method is custom and will not be overwritten on another generation.
     * This method corresponds to the database table contact
     *
     */
    int getLastInsertId();     
    
}