package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.empirestateids.domain.CvxCatalogs;
import com.empirestateids.domain.CvxCatalogsExample;
import com.empirestateids.domain.CvxCatalogsKey;

public interface CvxCatalogsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	long countByExample(CvxCatalogsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	int deleteByExample(CvxCatalogsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	int deleteByPrimaryKey(CvxCatalogsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	int insert(CvxCatalogs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	int insertSelective(CvxCatalogs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	List<CvxCatalogs> selectByExample(CvxCatalogsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	CvxCatalogs selectByPrimaryKey(CvxCatalogsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	int updateByExampleSelective(@Param("row") CvxCatalogs row, @Param("example") CvxCatalogsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	int updateByExample(@Param("row") CvxCatalogs row, @Param("example") CvxCatalogsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	int updateByPrimaryKeySelective(CvxCatalogs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cvx_catalogs
	 * @mbg.generated  Thu Jul 04 10:38:23 EDT 2024
	 */
	int updateByPrimaryKey(CvxCatalogs row);


	/**
	 * Charlie DiDonato custom. 07/04/2024. This method corresponds to the database table cvx_catalog
	 */
	int deleteAll();

}