package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.Email;
import com.empirestateids.domain.EmailCriteria;

public interface EmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    int countByExample(EmailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    int deleteByExample(EmailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    int deleteByPrimaryKey(Integer emailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    int insert(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    int insertSelective(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    List<Email> selectByExampleWithRowbounds(EmailCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    List<Email> selectByExample(EmailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    Email selectByPrimaryKey(Integer emailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    int updateByExampleSelective(@Param("record") Email record, @Param("example") EmailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    int updateByExample(@Param("record") Email record, @Param("example") EmailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    int updateByPrimaryKeySelective(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated Sat Oct 20 15:48:33 EDT 2012
     */
    int updateByPrimaryKey(Email record);
}