package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.Events;
import com.empirestateids.domain.EventsCriteria;

public interface EventsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    int countByExample(EventsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    int deleteByExample(EventsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    int deleteByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    int insert(Events record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    int insertSelective(Events record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    List<Events> selectByExampleWithRowbounds(EventsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    List<Events> selectByExample(EventsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    Events selectByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    int updateByExampleSelective(@Param("record") Events record, @Param("example") EventsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    int updateByExample(@Param("record") Events record, @Param("example") EventsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    int updateByPrimaryKeySelective(Events record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Sun Jul 30 15:48:30 EDT 2017
     */
    int updateByPrimaryKey(Events record);
    
    /**
     * This method is custom and will not be overwritten on another generation.
     * Charlie D 09/20/2018
     * This method corresponds to the database table events
     *
     */
    int getLastInsertId();        
}