package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.GroupAuthority;
import com.empirestateids.domain.GroupAuthorityCriteria;

public interface GroupAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int countByExample(GroupAuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByExample(GroupAuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByPrimaryKey(Integer groupAuthorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insert(GroupAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insertSelective(GroupAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<GroupAuthority> selectByExampleWithRowbounds(GroupAuthorityCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<GroupAuthority> selectByExample(GroupAuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    GroupAuthority selectByPrimaryKey(Integer groupAuthorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExampleSelective(@Param("record") GroupAuthority record, @Param("example") GroupAuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExample(@Param("record") GroupAuthority record, @Param("example") GroupAuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKeySelective(GroupAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authority
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKey(GroupAuthority record);
}