package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.GroupMember;
import com.empirestateids.domain.GroupMemberCriteria;

public interface GroupMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int countByExample(GroupMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByExample(GroupMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByPrimaryKey(Integer groupMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insert(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insertSelective(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<GroupMember> selectByExampleWithRowbounds(GroupMemberCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<GroupMember> selectByExample(GroupMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    GroupMember selectByPrimaryKey(Integer groupMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExampleSelective(@Param("record") GroupMember record, @Param("example") GroupMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExample(@Param("record") GroupMember record, @Param("example") GroupMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKeySelective(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKey(GroupMember record);
}