package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.empirestateids.domain.Icd11;
import com.empirestateids.domain.Icd11Example;

public interface Icd11Mapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	long countByExample(Icd11Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int deleteByExample(Icd11Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int insert(Icd11 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int insertSelective(Icd11 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	List<Icd11> selectByExampleWithBLOBs(Icd11Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	List<Icd11> selectByExample(Icd11Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	Icd11 selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int updateByExampleSelective(@Param("row") Icd11 row, @Param("example") Icd11Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int updateByExampleWithBLOBs(@Param("row") Icd11 row, @Param("example") Icd11Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int updateByExample(@Param("row") Icd11 row, @Param("example") Icd11Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int updateByPrimaryKeySelective(Icd11 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int updateByPrimaryKeyWithBLOBs(Icd11 row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table icd11
	 * @mbg.generated  Fri Jul 19 19:37:48 EDT 2024
	 */
	int updateByPrimaryKey(Icd11 row);

	/**
     * Delete all rows from icd11
     * @return
     */
    int deleteAll();
}