package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.IdSeq;
import com.empirestateids.domain.IdSeqCriteria;

public interface IdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int countByExample(IdSeqCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByExample(IdSeqCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insert(IdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insertSelective(IdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<IdSeq> selectByExampleWithRowbounds(IdSeqCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<IdSeq> selectByExample(IdSeqCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    IdSeq selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExampleSelective(@Param("record") IdSeq record, @Param("example") IdSeqCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExample(@Param("record") IdSeq record, @Param("example") IdSeqCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKeySelective(IdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_seq
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKey(IdSeq record);
}