package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.IpowerliftId;
import com.empirestateids.domain.IpowerliftIdCriteria;

public interface IpowerliftIdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	long countByExample(IpowerliftIdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	int deleteByExample(IpowerliftIdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	int deleteByPrimaryKey(Integer ipowerliftId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	int insert(IpowerliftId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	int insertSelective(IpowerliftId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	List<IpowerliftId> selectByExampleWithRowbounds(IpowerliftIdCriteria example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	List<IpowerliftId> selectByExample(IpowerliftIdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	IpowerliftId selectByPrimaryKey(Integer ipowerliftId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	int updateByExampleSelective(@Param("record") IpowerliftId record, @Param("example") IpowerliftIdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	int updateByExample(@Param("record") IpowerliftId record, @Param("example") IpowerliftIdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	int updateByPrimaryKeySelective(IpowerliftId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ipowerlift_id
	 * @mbg.generated  Sat Sep 15 07:58:10 EDT 2018
	 */
	int updateByPrimaryKey(IpowerliftId record);

	/**
     * This method is custom and will not be overwritten on another generation.
     * This method corresponds to the database table article
     *
     */
    int getLastInsertId();	
}