package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.empirestateids.domain.Loinc;
import com.empirestateids.domain.LoincExample;
import com.empirestateids.domain.LoincWithBLOBs;



public interface LoincMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	long countByExample(LoincExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int deleteByExample(LoincExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int deleteByPrimaryKey(String loincNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int insert(LoincWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int insertSelective(LoincWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	List<LoincWithBLOBs> selectByExampleWithBLOBs(LoincExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	List<Loinc> selectByExample(LoincExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	LoincWithBLOBs selectByPrimaryKey(String loincNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int updateByExampleSelective(@Param("row") LoincWithBLOBs row, @Param("example") LoincExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int updateByExampleWithBLOBs(@Param("row") LoincWithBLOBs row, @Param("example") LoincExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int updateByExample(@Param("row") Loinc row, @Param("example") LoincExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int updateByPrimaryKeySelective(LoincWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int updateByPrimaryKeyWithBLOBs(LoincWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loinc
	 * @mbg.generated  Mon May 27 09:39:14 EDT 2024
	 */
	int updateByPrimaryKey(Loinc row);
}