package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.Lookup;
import com.empirestateids.domain.LookupCriteria;

public interface LookupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int countByExample(LookupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByExample(LookupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByPrimaryKey(Integer lookupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insert(Lookup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insertSelective(Lookup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<Lookup> selectByExampleWithRowbounds(LookupCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<Lookup> selectByExample(LookupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    Lookup selectByPrimaryKey(Integer lookupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExampleSelective(@Param("record") Lookup record, @Param("example") LookupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExample(@Param("record") Lookup record, @Param("example") LookupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKeySelective(Lookup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lookup
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKey(Lookup record);
}