package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.PersistentLogins;
import com.empirestateids.domain.PersistentLoginsCriteria;

public interface PersistentLoginsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int countByExample(PersistentLoginsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByExample(PersistentLoginsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int deleteByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insert(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int insertSelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<PersistentLogins> selectByExampleWithRowbounds(PersistentLoginsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    List<PersistentLogins> selectByExample(PersistentLoginsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    PersistentLogins selectByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExampleSelective(@Param("record") PersistentLogins record, @Param("example") PersistentLoginsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByExample(@Param("record") PersistentLogins record, @Param("example") PersistentLoginsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKeySelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Sat Aug 04 18:04:41 EDT 2012
     */
    int updateByPrimaryKey(PersistentLogins record);
}