package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.Person;
import com.empirestateids.domain.PersonCriteria;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    int countByExample(PersonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    int deleteByExample(PersonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    int deleteByPrimaryKey(Integer ipowerliftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    List<Person> selectByExampleWithRowbounds(PersonCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    List<Person> selectByExample(PersonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    Person selectByPrimaryKey(Integer ipowerliftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Aug 29 10:48:19 EDT 2012
     */
    int updateByPrimaryKey(Person record);
}