package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.Phone;
import com.empirestateids.domain.PhoneCriteria;

public interface PhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    int countByExample(PhoneCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    int deleteByExample(PhoneCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    int deleteByPrimaryKey(Integer phoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    int insert(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    int insertSelective(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    List<Phone> selectByExampleWithRowbounds(PhoneCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    List<Phone> selectByExample(PhoneCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    Phone selectByPrimaryKey(Integer phoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    int updateByExampleSelective(@Param("record") Phone record, @Param("example") PhoneCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    int updateByExample(@Param("record") Phone record, @Param("example") PhoneCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    int updateByPrimaryKeySelective(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Sep 02 19:21:18 EDT 2012
     */
    int updateByPrimaryKey(Phone record);
}