package com.empirestateids.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.empirestateids.domain.Registration;
import com.empirestateids.domain.RegistrationCriteria;

public interface RegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int countByExample(RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByExample(RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int deleteByPrimaryKey(Integer registrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insert(Registration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int insertSelective(Registration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<Registration> selectByExampleWithRowbounds(RegistrationCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    List<Registration> selectByExample(RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    Registration selectByPrimaryKey(Integer registrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExampleSelective(@Param("record") Registration record, @Param("example") RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByExample(@Param("record") Registration record, @Param("example") RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKeySelective(Registration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated Sat Aug 04 18:04:40 EDT 2012
     */
    int updateByPrimaryKey(Registration record);
}